[build]
builder = "NIXPACKS"
buildCommand = "pnpm run build"

[deploy]
startCommand = "node dist/watchWorker.js"
cronSchedule = "0 */6 * * *"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1
