import test from "node:test";import assert from "node:assert/strict";
import { buildSectorPrompt, generateSectorBriefing, REQUIRED_WARNING, SectorBriefingSchema, SECTOR_SYSTEM_PROMPT } from "./sectorAnalyzer";
const docs=[{id:"MDCG-1",title:"MDCG 2026-1",source:"MDCG",url:"https://example.test/mdcg",publishedAt:"2026-08-01",content:"Le guide décrit les attentes documentaires."},{id:"NBOG-1",title:"NBOG BPG 2026-1",source:"NBOG",url:"https://example.test/nbog",publishedAt:"2026-08-10",content:"La publication décrit une pratique d'audit."}];
const briefing={titre:"Attentes documentaires",resume:"Deux publications officielles décrivent les attentes documentaires.",pointsCles:[{titre:"Documentation",description:"Vérifier les enregistrements cités.",impact:"moyen",referentielsImpactes:["MDR"],source:"MDCG"}],tendances:[{description:"Renforcement documenté dans les sources",signal:"modere",horizon:"court_terme",source:"NBOG"}],actionsRecommandees:[{action:"Revoir les preuves",priorite:"moyenne",referentiel:"MDR",echeance:null}],niveauConfiance:"moyen",sourcesAnalysees:["MDCG","NBOG"],dateAnalyse:"2026-09-02",periodeCouverte:"août 2026",avertissement:REQUIRED_WARNING};
test("le prompt interdit toute invention",()=>{assert.match(SECTOR_SYSTEM_PROMPT,/n'inventes JAMAIS/);assert.match(buildSectorPrompt("audit_trends",docs,"MDR"),/DOCUMENTS RÉELS/);});
test("le schéma rejette un briefing sans sources",()=>{assert.equal(SectorBriefingSchema.safeParse({...briefing,sourcesAnalysees:[]}).success,false);});
test("l'avertissement exact est obligatoire",()=>{assert.equal(SectorBriefingSchema.safeParse({...briefing,avertissement:"optionnel"}).success,false);});
test("une réponse IA structurée et sourcée est acceptée",async()=>{const client={messages:{create:async()=>({content:[{type:"text",text:JSON.stringify(briefing)}]})}} as any;const result=await generateSectorBriefing("audit_trends",docs,"MDR",client);assert.equal(result.niveauConfiance,"moyen");});
test("une source unique ne peut pas déclarer une confiance élevée",async()=>{const client={messages:{create:async()=>({content:[{type:"text",text:JSON.stringify({...briefing,niveauConfiance:"eleve",sourcesAnalysees:["MDCG"]})}]})}} as any;await assert.rejects(()=>generateSectorBriefing("audit_trends",docs.slice(0,1),"MDR",client),/source unique/);});
