import { and, eq, gte, inArray } from "drizzle-orm";
import { audit_responses, audits, questions } from "../../../drizzle/schema";
import { getDb } from "../../db";
import { classifyNonConformityResponse } from "../../capa/capaEngine";

export type TrendRow={auditId:number;questionKey:string;responseValue:string;createdAt:Date;questionText:string;processName:string|null;criticality:string};
export interface AuditTrends {referentialId:number;periodDays:number;calculatedAt:string;dataQuality:"insuffisant"|"indicatif"|"significatif";topNCQuestions:any[];topNCProcessus:any[];evolutionConformite:any[];totalAuditsAnalyses:number;totalReponsesAnalysees:number;avertissement:string|null}
export function calculateTrendsFromRows(referentialId:number,periodDays:number,rows:TrendRow[]):AuditTrends{
 const total=rows.length, auditsCount=new Set(rows.map(r=>r.auditId)).size; const quality=total<50?"insuffisant":total<200?"indicatif":"significatif";
 const byQ=new Map<string,TrendRow[]>(),byP=new Map<string,TrendRow[]>();for(const r of rows){byQ.set(r.questionKey,[...(byQ.get(r.questionKey)??[]),r]);const p=r.processName||"Non renseigné";byP.set(p,[...(byP.get(p)??[]),r]);}
 const rate=(rs:TrendRow[])=>Math.round(rs.filter(r=>classifyNonConformityResponse(r.responseValue)).length/rs.length*1000)/10;
 const topNCQuestions=[...byQ.entries()].filter(([,v])=>v.length>=3).map(([questionKey,v])=>({questionKey,questionExtrait:v[0].questionText.slice(0,100),processus:v[0].processName,criticality:v[0].criticality,totalReponses:v.length,totalNC:v.filter(r=>classifyNonConformityResponse(r.responseValue)).length,tauxNC:rate(v)})).sort((a,b)=>b.tauxNC-a.tauxNC).slice(0,10);
 const topNCProcessus=[...byP.entries()].map(([processus,v])=>({processus,totalReponses:v.length,totalNC:v.filter(r=>classifyNonConformityResponse(r.responseValue)).length,tauxNC:rate(v)})).sort((a,b)=>b.tauxNC-a.tauxNC);
 const months=new Map<string,TrendRow[]>();for(const r of rows){const m=r.createdAt.toISOString().slice(0,7);months.set(m,[...(months.get(m)??[]),r]);}const evolutionConformite=[...months.entries()].sort().map(([mois,v])=>({mois,totalReponses:v.length,conformes:v.filter(r=>["compliant","conforme","yes"].includes(String(r.responseValue).toLowerCase())).length,tauxConformite:Math.round(v.filter(r=>["compliant","conforme","yes"].includes(String(r.responseValue).toLowerCase())).length/v.length*1000)/10}));
 return {referentialId,periodDays,calculatedAt:new Date().toISOString(),dataQuality:quality,topNCQuestions,topNCProcessus,evolutionConformite,totalAuditsAnalyses:auditsCount,totalReponsesAnalysees:total,avertissement:quality==="insuffisant"?"Données insuffisantes pour des tendances significatives. Ces chiffres seront plus représentatifs avec plus d'audits.":null};
}
export async function calculateAuditTrends(userId:number,referentialId:number,periodDays=90){const db=await getDb();if(!db)throw new Error("Database unavailable");const qs=await db.select().from(questions).where(eq(questions.referentialId,referentialId));const validQuestions=qs.filter((q):q is typeof q & {questionKey:string}=>Boolean(q.questionKey));const qMap=new Map(validQuestions.map(q=>[q.questionKey,q]));if(!validQuestions.length)return calculateTrendsFromRows(referentialId,periodDays,[]);const since=new Date(Date.now()-periodDays*86400000);const responses=await db.select().from(audit_responses).where(and(eq(audit_responses.userId,userId),gte(audit_responses.createdAt,since),inArray(audit_responses.questionKey,validQuestions.map(q=>q.questionKey))));return calculateTrendsFromRows(referentialId,periodDays,responses.map(r=>{const q=qMap.get(r.questionKey)!;return{auditId:r.auditId,questionKey:r.questionKey,responseValue:r.responseValue??"",createdAt:r.createdAt,questionText:q.questionText??q.title??r.questionKey,processName:q.processDetail??null,criticality:q.criticality??"medium"}}));}
export async function countUserAudits(userId:number){const db=await getDb();if(!db)return 0;return (await db.select({id:audits.id}).from(audits).where(eq(audits.userId,userId))).length;}
