CREATE TABLE IF NOT EXISTS referentiels (
  id INT NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) NULL,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(50) NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS processus (
  id INT NOT NULL AUTO_INCREMENT,
  code VARCHAR(50) NULL,
  name VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
