import { MdrQuestion } from "./types";

export const allMdrQuestions: MdrQuestion[] = [
  // MDR - Article 1 - Objet et champ d’application
  {
    id: "MDR-ART-1-Q1",
    text: "Comment avez-vous déterminé que vos produits relèvent du champ MDR ?",
    chapter: "Article 1",
    topic: "Objet et champ d’application",
    article: "1",
    isoClause: "N/A",
    process: "Gouvernance réglementaire",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-1-Q2",
    text: "Disposez-vous d’une justification écrite de qualification réglementaire ?",
    chapter: "Article 1",
    topic: "Objet et champ d’application",
    article: "1",
    isoClause: "N/A",
    process: "Gouvernance réglementaire",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-1-Q3",
    text: "Comment traitez-vous les produits frontières (logiciel, accessoire, service associé) ?",
    chapter: "Article 1",
    topic: "Objet et champ d’application",
    article: "1",
    isoClause: "N/A",
    process: "Affaires réglementaires (RA)",
    economicRole: "Fabricant",
    criticality: "medium",
  },
  {
    id: "MDR-ART-1-Q4",
    text: "Qui valide formellement la qualification DM ?",
    chapter: "Article 1",
    topic: "Objet et champ d’application",
    article: "1",
    isoClause: "N/A",
    process: "Gouvernance réglementaire",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-1-Q5",
    text: "Comment assurez-vous une veille réglementaire sur l’évolution du champ MDR ?",
    chapter: "Article 1",
    topic: "Objet et champ d’application",
    article: "1",
    isoClause: "N/A",
    process: "Affaires réglementaires (RA)",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 2 - Définitions
  {
    id: "MDR-ART-2-Q1",
    text: "Où sont formalisées les définitions réglementaires clés ?",
    chapter: "Article 2",
    topic: "Définitions",
    article: "2",
    isoClause: "N/A",
    process: "Gouvernance QMS",
    economicRole: "Fabricant",
    criticality: "medium",
  },
  {
    id: "MDR-ART-2-Q2",
    text: "Comment assurez-vous l’alignement du vocabulaire interne avec le MDR ?",
    chapter: "Article 2",
    topic: "Définitions",
    article: "2",
    isoClause: "N/A",
    process: "Documentation réglementaire",
    economicRole: "Fabricant",
    criticality: "medium",
  },
  {
    id: "MDR-ART-2-Q3",
    text: "Les formations internes couvrent-elles les termes critiques MDR ?",
    chapter: "Article 2",
    topic: "Définitions",
    article: "2",
    isoClause: "N/A",
    process: "Gouvernance QMS",
    economicRole: "Fabricant",
    criticality: "medium",
  },
  {
    id: "MDR-ART-2-Q4",
    text: "Comment évitez-vous les interprétations divergentes entre services ?",
    chapter: "Article 2",
    topic: "Définitions",
    article: "2",
    isoClause: "N/A",
    process: "Gouvernance QMS",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 3 - Groupe de coordination DM
  {
    id: "MDR-ART-3-Q1",
    text: "Comment tenez-vous compte des positions et lignes directrices européennes ?",
    chapter: "Article 3",
    topic: "Groupe de coordination DM",
    article: "3",
    isoClause: "N/A",
    process: "Gouvernance réglementaire",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-3-Q2",
    text: "Avez-vous identifié les documents MDCG applicables ?",
    chapter: "Article 3",
    topic: "Groupe de coordination DM",
    article: "3",
    isoClause: "N/A",
    process: "Gouvernance réglementaire",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-3-Q3",
    text: "Comment les positions du MDCG sont-elles intégrées dans votre QMS ?",
    chapter: "Article 3",
    topic: "Groupe de coordination DM",
    article: "3",
    isoClause: "N/A",
    process: "Gouvernance QMS",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 4 - Statut réglementaire
  {
    id: "MDR-ART-4-Q1",
    text: "Disposez-vous d’une procédure d’évaluation de changement réglementaire ?",
    chapter: "Article 4",
    topic: "Statut réglementaire",
    article: "4",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-4-Q2",
    text: "Comment identifiez-vous un changement impactant le statut DM ?",
    chapter: "Article 4",
    topic: "Statut réglementaire",
    article: "4",
    isoClause: "N/A",
    process: "Change control",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-4-Q3",
    text: "Qui valide la requalification réglementaire ?",
    chapter: "Article 4",
    topic: "Statut réglementaire",
    article: "4",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-4-Q4",
    text: "Comment est tracée la décision réglementaire ?",
    chapter: "Article 4",
    topic: "Statut réglementaire",
    article: "4",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 5 - Mise sur le marché et mise en service
  {
    id: "MDR-ART-5-Q1",
    text: "Comment garantissez-vous que seuls des DM conformes MDR sont mis sur le marché ?",
    chapter: "Article 5",
    topic: "Mise sur le marché et mise en service",
    article: "5",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-5-Q2",
    text: "Quelle preuve démontre la conformité avant première mise sur le marché ?",
    chapter: "Article 5",
    topic: "Mise sur le marché et mise en service",
    article: "5",
    isoClause: "N/A",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-5-Q3",
    text: "Comment gérez-vous les différences mise sur le marché / mise en service ?",
    chapter: "Article 5",
    topic: "Mise sur le marché et mise en service",
    article: "5",
    isoClause: "N/A",
    process: "Release produit",
    economicRole: "Fabricant",
    criticality: "medium",
  },
  {
    id: "MDR-ART-5-Q4",
    text: "Existe-t-il un go/no-go réglementaire formalisé ?",
    chapter: "Article 5",
    topic: "Mise sur le marché et mise en service",
    article: "5",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 6 - Vente à distance
  {
    id: "MDR-ART-6-Q1",
    text: "Comment garantissez-vous la conformité MDR des ventes en ligne ?",
    chapter: "Article 6",
    topic: "Vente à distance",
    article: "6",
    isoClause: "N/A",
    process: "Distribution",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-6-Q2",
    text: "Les informations obligatoires sont-elles accessibles avant achat ?",
    chapter: "Article 6",
    topic: "Vente à distance",
    article: "6",
    isoClause: "N/A",
    process: "Marketing / e-commerce",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-6-Q3",
    text: "Comment assurez-vous la traçabilité des ventes à distance ?",
    chapter: "Article 6",
    topic: "Vente à distance",
    article: "6",
    isoClause: "N/A",
    process: "Distribution",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-6-Q4",
    text: "Existe-t-il une revue réglementaire du contenu web ?",
    chapter: "Article 6",
    topic: "Vente à distance",
    article: "6",
    isoClause: "N/A",
    process: "Marketing / e-commerce",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 7 - Allégations
  {
    id: "MDR-ART-7-Q1",
    text: "Comment validez-vous les allégations cliniques et performances ?",
    chapter: "Article 7",
    topic: "Allégations",
    article: "7",
    isoClause: "N/A",
    process: "Marketing",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-7-Q2",
    text: "Existe-t-il une revue réglementaire du marketing ?",
    chapter: "Article 7",
    topic: "Allégations",
    article: "7",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-7-Q3",
    text: "Comment évitez-vous toute allégation trompeuse ?",
    chapter: "Article 7",
    topic: "Allégations",
    article: "7",
    isoClause: "N/A",
    process: "Marketing",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-7-Q4",
    text: "Comment sont gérées les communications commerciales internationales ?",
    chapter: "Article 7",
    topic: "Allégations",
    article: "7",
    isoClause: "N/A",
    process: "Marketing",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 8 - Normes harmonisées
  {
    id: "MDR-ART-8-Q1",
    text: "Quelles normes harmonisées appliquez-vous ?",
    chapter: "Article 8",
    topic: "Normes harmonisées",
    article: "8",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-8-Q2",
    text: "Comment assurez-vous leur mise à jour ?",
    chapter: "Article 8",
    topic: "Normes harmonisées",
    article: "8",
    isoClause: "N/A",
    process: "Gestion des normes",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-8-Q3",
    text: "Comment traitez-vous les écarts à une norme harmonisée ?",
    chapter: "Article 8",
    topic: "Normes harmonisées",
    article: "8",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-8-Q4",
    text: "Où est documentée la présomption de conformité ?",
    chapter: "Article 8",
    topic: "Normes harmonisées",
    article: "8",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 9 - Spécifications communes
  {
    id: "MDR-ART-9-Q1",
    text: "Avez-vous identifié des CS applicables ?",
    chapter: "Article 9",
    topic: "Spécifications communes",
    article: "9",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-9-Q2",
    text: "Comment démontrez-vous leur prise en compte complète ?",
    chapter: "Article 9",
    topic: "Spécifications communes",
    article: "9",
    isoClause: "N/A",
    process: "Gestion des exigences",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-9-Q3",
    text: "Comment gérez-vous une CS nouvelle ou modifiée ?",
    chapter: "Article 9",
    topic: "Spécifications communes",
    article: "9",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 10 - Obligations générales du fabricant
  {
    id: "MDR-ART-10-Q1",
    text: "Votre QMS couvre-t-il l’intégralité des exigences MDR ?",
    chapter: "Article 10",
    topic: "Obligations générales du fabricant",
    article: "10",
    isoClause: "N/A",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-10-Q2",
    text: "Comment démontrez-vous la conformité sur tout le cycle de vie ?",
    chapter: "Article 10",
    topic: "Obligations générales du fabricant",
    article: "10",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-10-Q3",
    text: "Comment est intégrée la gestion des risques ISO 14971 ?",
    chapter: "Article 10",
    topic: "Obligations générales du fabricant",
    article: "10",
    isoClause: "N/A",
    process: "Gestion des risques",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-10-Q4",
    text: "Comment est structurée la PMS / PMCF ?",
    chapter: "Article 10",
    topic: "Obligations générales du fabricant",
    article: "10",
    isoClause: "N/A",
    process: "PMS / PMCF",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-10-Q5",
    text: "Qui est responsable de la conformité réglementaire globale ?",
    chapter: "Article 10",
    topic: "Obligations générales du fabricant",
    article: "10",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-10-Q6",
    text: "Comment traitez-vous les non-conformités réglementaires ?",
    chapter: "Article 10",
    topic: "Obligations générales du fabricant",
    article: "10",
    isoClause: "N/A",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-10-Q7",
    text: "Existe-t-il une revue périodique de conformité MDR ?",
    chapter: "Article 10",
    topic: "Obligations générales du fabricant",
    article: "10",
    isoClause: "N/A",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // ISO 13485 - Clause 4 - Système de management de la qualité
  {
    id: "ISO-CLAUSE-4-Q1",
    text: "Le périmètre du QMS est-il clairement défini ?",
    chapter: "Clause 4",
    topic: "Système de management de la qualité",
    article: "N/A",
    isoClause: "4.1",
    process: "Gouvernance QMS",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-4-Q2",
    text: "Les processus sont-ils identifiés, séquencés et maîtrisés ?",
    chapter: "Clause 4",
    topic: "Système de management de la qualité",
    article: "N/A",
    isoClause: "4.1",
    process: "Pilotage des processus",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-4-Q3",
    text: "Comment sont gérées les exigences réglementaires applicables ?",
    chapter: "Clause 4",
    topic: "Système de management de la qualité",
    article: "N/A",
    isoClause: "4.1",
    process: "Gouvernance QMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "ISO-CLAUSE-4-Q4",
    text: "Comment démontrez-vous la maîtrise documentaire ?",
    chapter: "Clause 4",
    topic: "Système de management de la qualité",
    article: "N/A",
    isoClause: "4.2",
    process: "Documentation réglementaire",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-4-Q5",
    text: "Les enregistrements sont-ils traçables, protégés et exploitables ?",
    chapter: "Clause 4",
    topic: "Système de management de la qualité",
    article: "N/A",
    isoClause: "4.2.5",
    process: "Documentation réglementaire",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // ISO 13485 - Clause 5 - Responsabilité de la direction
  {
    id: "ISO-CLAUSE-5-Q1",
    text: "La direction démontre-t-elle son engagement QMS ?",
    chapter: "Clause 5",
    topic: "Responsabilité de la direction",
    article: "N/A",
    isoClause: "5.1",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-5-Q2",
    text: "Les objectifs qualité sont-ils mesurables et suivis ?",
    chapter: "Clause 5",
    topic: "Responsabilité de la direction",
    article: "N/A",
    isoClause: "5.4.1",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },
  {
    id: "ISO-CLAUSE-5-Q3",
    text: "La revue de direction couvre-t-elle MDR, risques et performance ?",
    chapter: "Clause 5",
    topic: "Responsabilité de la direction",
    article: "N/A",
    isoClause: "5.6",
    process: "Revue de direction",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "ISO-CLAUSE-5-Q4",
    text: "Comment les ressources sont-elles allouées ?",
    chapter: "Clause 5",
    topic: "Responsabilité de la direction",
    article: "N/A",
    isoClause: "5.5.1",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },
  {
    id: "ISO-CLAUSE-5-Q5",
    text: "Comment les responsabilités sont-elles définies et communiquées ?",
    chapter: "Clause 5",
    topic: "Responsabilité de la direction",
    article: "N/A",
    isoClause: "5.5.1",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 11 - Mandataire
  {
    id: "MDR-ART-11-Q1",
    text: "Le fabricant hors UE a-t-il désigné un mandataire MDR unique ?",
    chapter: "Article 11",
    topic: "Mandataire",
    article: "11",
    isoClause: "N/A",
    process: "Affaires réglementaires",
    economicRole: "Mandataire",
    criticality: "critical",
  },
  {
    id: "MDR-ART-11-Q2",
    text: "Le mandat écrit couvre-t-il l’intégralité des responsabilités exigées par l’article 11 ?",
    chapter: "Article 11",
    topic: "Mandataire",
    article: "11",
    isoClause: "N/A",
    process: "Gouvernance des acteurs",
    economicRole: "Mandataire",
    criticality: "critical",
  },
  {
    id: "MDR-ART-11-Q3",
    text: "Comment le mandataire est-il impliqué dans la vigilance et la PMS ?",
    chapter: "Article 11",
    topic: "Mandataire",
    article: "11",
    isoClause: "N/A",
    process: "Vigilance",
    economicRole: "Mandataire",
    criticality: "high",
  },
  {
    id: "MDR-ART-11-Q4",
    text: "Comment sont gérés les changements de mandataire ?",
    chapter: "Article 11",
    topic: "Mandataire",
    article: "11",
    isoClause: "N/A",
    process: "Affaires réglementaires",
    economicRole: "Mandataire",
    criticality: "high",
  },
  {
    id: "MDR-ART-11-Q5",
    text: "Comment assurez-vous la communication efficace fabricant ↔ mandataire ?",
    chapter: "Article 11",
    topic: "Mandataire",
    article: "11",
    isoClause: "N/A",
    process: "Affaires réglementaires",
    economicRole: "Mandataire",
    criticality: "medium",
  },

  // MDR - Article 12 - Procédures nationales spécifiques
  {
    id: "MDR-ART-12-Q1",
    text: "Comment identifiez-vous les exigences nationales additionnelles ?",
    chapter: "Article 12",
    topic: "Procédures nationales spécifiques",
    article: "12",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-12-Q2",
    text: "Existe-t-il une veille réglementaire pays par pays ?",
    chapter: "Article 12",
    topic: "Procédures nationales spécifiques",
    article: "12",
    isoClause: "N/A",
    process: "Veille réglementaire",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-12-Q3",
    text: "Comment ces exigences sont-elles intégrées dans le QMS ?",
    chapter: "Article 12",
    topic: "Procédures nationales spécifiques",
    article: "12",
    isoClause: "N/A",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-12-Q4",
    text: "Qui valide la conformité locale avant commercialisation ?",
    chapter: "Article 12",
    topic: "Procédures nationales spécifiques",
    article: "12",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 13 - Obligations générales de l’importateur
  {
    id: "MDR-ART-13-Q1",
    text: "Comment l’importateur vérifie-t-il la conformité MDR avant mise sur le marché ?",
    chapter: "Article 13",
    topic: "Obligations générales de l’importateur",
    article: "13",
    isoClause: "N/A",
    process: "Importation",
    economicRole: "Importateur",
    criticality: "critical",
  },
  {
    id: "MDR-ART-13-Q2",
    text: "Dispose-t-il d’une procédure de contrôle documentaire ?",
    chapter: "Article 13",
    topic: "Obligations générales de l’importateur",
    article: "13",
    isoClause: "N/A",
    process: "Supply chain",
    economicRole: "Importateur",
    criticality: "high",
  },
  {
    id: "MDR-ART-13-Q3",
    text: "Comment est vérifiée la présence du marquage CE et UDI ?",
    chapter: "Article 13",
    topic: "Obligations générales de l’importateur",
    article: "13",
    isoClause: "N/A",
    process: "Importation",
    economicRole: "Importateur",
    criticality: "high",
  },
  {
    id: "MDR-ART-13-Q4",
    text: "Comment sont gérés les DM non conformes ?",
    chapter: "Article 13",
    topic: "Obligations générales de l’importateur",
    article: "13",
    isoClause: "N/A",
    process: "QMS étendu",
    economicRole: "Importateur",
    criticality: "critical",
  },
  {
    id: "MDR-ART-13-Q5",
    text: "Comment l’importateur contribue-t-il à la traçabilité et à la vigilance ?",
    chapter: "Article 13",
    topic: "Obligations générales de l’importateur",
    article: "13",
    isoClause: "N/A",
    process: "Vigilance",
    economicRole: "Importateur",
    criticality: "high",
  },

  // MDR - Article 14 - Obligations générales du distributeur
  {
    id: "MDR-ART-14-Q1",
    text: "Comment le distributeur vérifie-t-il la conformité des DM reçus ?",
    chapter: "Article 14",
    topic: "Obligations générales du distributeur",
    article: "14",
    isoClause: "N/A",
    process: "Distribution",
    economicRole: "Distributeur",
    criticality: "high",
  },
  {
    id: "MDR-ART-14-Q2",
    text: "Existe-t-il une checklist de conformité MDR à réception ?",
    chapter: "Article 14",
    topic: "Obligations générales du distributeur",
    article: "14",
    isoClause: "N/A",
    process: "Logistique",
    economicRole: "Distributeur",
    criticality: "high",
  },
  {
    id: "MDR-ART-14-Q3",
    text: "Comment sont gérés les DM suspects ou non conformes ?",
    chapter: "Article 14",
    topic: "Obligations générales du distributeur",
    article: "14",
    isoClause: "N/A",
    process: "Vigilance",
    economicRole: "Distributeur",
    criticality: "critical",
  },
  {
    id: "MDR-ART-14-Q4",
    text: "Comment le distributeur contribue-t-il à la traçabilité aval ?",
    chapter: "Article 14",
    topic: "Obligations générales du distributeur",
    article: "14",
    isoClause: "N/A",
    process: "Traçabilité",
    economicRole: "Distributeur",
    criticality: "high",
  },
  {
    id: "MDR-ART-14-Q5",
    text: "Comment est assurée la remontée d’information vers le fabricant ?",
    chapter: "Article 14",
    topic: "Obligations générales du distributeur",
    article: "14",
    isoClause: "N/A",
    process: "Vigilance",
    economicRole: "Distributeur",
    criticality: "medium",
  },

  // MDR - Article 15 - Personne chargée de veiller au respect de la réglementation (PRRC)
  {
    id: "MDR-ART-15-Q1",
    text: "Une PRRC est-elle formellement désignée ?",
    chapter: "Article 15",
    topic: "PRRC",
    article: "15",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-15-Q2",
    text: "Les compétences réglementaires sont-elles démontrées ?",
    chapter: "Article 15",
    topic: "PRRC",
    article: "15",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-15-Q3",
    text: "La PRRC a-t-elle une autorité réelle dans l’organisation ?",
    chapter: "Article 15",
    topic: "PRRC",
    article: "15",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-15-Q4",
    text: "Comment est assurée la continuité en cas d’absence ?",
    chapter: "Article 15",
    topic: "PRRC",
    article: "15",
    isoClause: "N/A",
    process: "Ressources humaines",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-15-Q5",
    text: "La PRRC est-elle impliquée dans libération produit, PMS, vigilance ?",
    chapter: "Article 15",
    topic: "PRRC",
    article: "15",
    isoClause: "N/A",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 16 - Cas dans lesquels les obligations du fabricant s’appliquent aux importateurs ou distributeurs
  {
    id: "MDR-ART-16-Q1",
    text: "Comment identifiez-vous un changement entraînant une requalification fabricant ?",
    chapter: "Article 16",
    topic: "Obligations du fabricant s’appliquant aux importateurs ou distributeurs",
    article: "16",
    isoClause: "N/A",
    process: "Change control",
    economicRole: "Importateur",
    criticality: "high",
  },
  {
    id: "MDR-ART-16-Q2",
    text: "Existe-t-il une procédure de gestion des modifications ?",
    chapter: "Article 16",
    topic: "Obligations du fabricant s’appliquant aux importateurs ou distributeurs",
    article: "16",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Importateur",
    criticality: "high",
  },
  {
    id: "MDR-ART-16-Q3",
    text: "Comment est documentée la décision réglementaire ?",
    chapter: "Article 16",
    topic: "Obligations du fabricant s’appliquant aux importateurs ou distributeurs",
    article: "16",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Importateur",
    criticality: "medium",
  },
  {
    id: "MDR-ART-16-Q4",
    text: "Qui valide le nouveau rôle réglementaire ?",
    chapter: "Article 16",
    topic: "Obligations du fabricant s’appliquant aux importateurs ou distributeurs",
    article: "16",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Importateur",
    criticality: "high",
  },
  {
    id: "MDR-ART-16-Q5",
    text: "Comment sont gérées les responsabilités MDR associées ?",
    chapter: "Article 16",
    topic: "Obligations du fabricant s’appliquant aux importateurs ou distributeurs",
    article: "16",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Importateur",
    criticality: "high",
  },

  // MDR - Article 17 - Dispositifs remis à neuf / reconditionnés
  {
    id: "MDR-ART-17-Q1",
    text: "Les dispositifs remis à neuf sont-ils explicitement couverts par le QMS ?",
    chapter: "Article 17",
    topic: "Dispositifs remis à neuf / reconditionnés",
    article: "17",
    isoClause: "N/A",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-17-Q2",
    text: "Comment démontrez-vous la sécurité et performance après reconditionnement ?",
    chapter: "Article 17",
    topic: "Dispositifs remis à neuf / reconditionnés",
    article: "17",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-17-Q3",
    text: "Comment est assurée la traçabilité des opérations ?",
    chapter: "Article 17",
    topic: "Dispositifs remis à neuf / reconditionnés",
    article: "17",
    isoClause: "N/A",
    process: "Gestion des risques",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-17-Q4",
    text: "Existe-t-il une évaluation de risque spécifique ?",
    chapter: "Article 17",
    topic: "Dispositifs remis à neuf / reconditionnés",
    article: "17",
    isoClause: "N/A",
    process: "Gestion des risques",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-17-Q5",
    text: "Comment informez-vous les utilisateurs finaux ?",
    chapter: "Article 17",
    topic: "Dispositifs remis à neuf / reconditionnés",
    article: "17",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 18 - Carte implant et informations patient
  {
    id: "MDR-ART-18-Q1",
    text: "Les cartes implant sont-elles conformes au MDR ?",
    chapter: "Article 18",
    topic: "Carte implant et informations patient",
    article: "18",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-18-Q2",
    text: "Comment assurez-vous la complétude et la lisibilité des informations patient ?",
    chapter: "Article 18",
    topic: "Carte implant et informations patient",
    article: "18",
    isoClause: "N/A",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-18-Q3",
    text: "Comment gérez-vous les mises à jour d’information ?",
    chapter: "Article 18",
    topic: "Carte implant et informations patient",
    article: "18",
    isoClause: "N/A",
    process: "Communication patient",
    economicRole: "Fabricant",
    criticality: "medium",
  },
  {
    id: "MDR-ART-18-Q4",
    text: "Existe-t-il une validation réglementaire des supports patient ?",
    chapter: "Article 18",
    topic: "Carte implant et informations patient",
    article: "18",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 19 - Déclaration UE de conformité
  {
    id: "MDR-ART-19-Q1",
    text: "La DoC UE couvre-t-elle toutes les exigences MDR applicables ?",
    chapter: "Article 19",
    topic: "Déclaration UE de conformité",
    article: "19",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-19-Q2",
    text: "Est-elle signée par une personne autorisée ?",
    chapter: "Article 19",
    topic: "Déclaration UE de conformité",
    article: "19",
    isoClause: "N/A",
    process: "Libération réglementaire",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-19-Q3",
    text: "Comment est assurée la mise à jour de la DoC ?",
    chapter: "Article 19",
    topic: "Déclaration UE de conformité",
    article: "19",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-19-Q4",
    text: "Où est tracée la cohérence DoC ↔ documentation technique ?",
    chapter: "Article 19",
    topic: "Déclaration UE de conformité",
    article: "19",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-19-Q5",
    text: "La DoC est-elle mise à disposition sur demande ?",
    chapter: "Article 19",
    topic: "Déclaration UE de conformité",
    article: "19",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 20 - Marquage CE
  {
    id: "MDR-ART-20-Q1",
    text: "Comment garantissez-vous que le marquage CE est apposé correctement ?",
    chapter: "Article 20",
    topic: "Marquage CE",
    article: "20",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-20-Q2",
    text: "Comment est vérifiée la cohérence CE ?",
    chapter: "Article 20",
    topic: "Marquage CE",
    article: "20",
    isoClause: "N/A",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-20-Q3",
    text: "Comment est vérifiée la cohérence CE ?",
    chapter: "Article 20",
    topic: "Marquage CE",
    article: "20",
    isoClause: "N/A",
    process: "Distribution",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 21 - Libre circulation
  {
    id: "MDR-ART-21-Q1",
    text: "Comment assurez-vous la libre circulation de vos DM conformes ?",
    chapter: "Article 21",
    topic: "Libre circulation",
    article: "21",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 22 - Systèmes et nécessaires
  {
    id: "MDR-ART-22-Q1",
    text: "Comment sont gérés les systèmes et nécessaires ?",
    chapter: "Article 22",
    topic: "Systèmes et nécessaires",
    article: "22",
    isoClause: "N/A",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 23 - Parties et composants
  {
    id: "MDR-ART-23-Q1",
    text: "Comment sont gérées les parties et composants ?",
    chapter: "Article 23",
    topic: "Parties et composants",
    article: "23",
    isoClause: "N/A",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 24 - DM à usage unique
  {
    id: "MDR-ART-24-Q1",
    text: "Comment sont gérés les DM à usage unique ?",
    chapter: "Article 24",
    topic: "DM à usage unique",
    article: "24",
    isoClause: "N/A",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 25 - Traçabilité
  {
    id: "MDR-ART-25-Q1",
    text: "Comment identifiez-vous les opérateurs économiques dans la chaîne ?",
    chapter: "Article 25",
    topic: "Traçabilité",
    article: "25",
    isoClause: "7.5.3",
    process: "Traçabilité",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-25-Q2",
    text: "Comment assurez-vous la traçabilité amont/aval sur 10 ans ?",
    chapter: "Article 25",
    topic: "Traçabilité",
    article: "25",
    isoClause: "7.5.3",
    process: "Traçabilité",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "MDR-ART-25-Q3",
    text: "Existe-t-il une procédure de rappel produit ?",
    chapter: "Article 25",
    topic: "Traçabilité",
    article: "25",
    isoClause: "8.3.3",
    process: "Vigilance",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "MDR-ART-25-Q4",
    text: "Comment testez-vous l’efficacité de la traçabilité ?",
    chapter: "Article 25",
    topic: "Traçabilité",
    article: "25",
    isoClause: "7.5.3",
    process: "Traçabilité",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 26 - EUDAMED
  {
    id: "MDR-ART-26-Q1",
    text: "Qui est responsable des enregistrements EUDAMED ?",
    chapter: "Article 26",
    topic: "EUDAMED",
    article: "26",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 27 - UDI
  {
    id: "MDR-ART-27-Q1",
    text: "Comment est intégré l’UDI dans la PMS et la vigilance ?",
    chapter: "Article 27",
    topic: "UDI",
    article: "27",
    isoClause: "7.5.3",
    process: "Traçabilité",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 28 - Enregistrement des opérateurs économiques
  {
    id: "MDR-ART-28-Q1",
    text: "Tous les opérateurs sont-ils enregistrés et à jour ?",
    chapter: "Article 28",
    topic: "Enregistrement des opérateurs économiques",
    article: "28",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 29 - Enregistrement des dispositifs
  {
    id: "MDR-ART-29-Q1",
    text: "Tous les dispositifs sont-ils enregistrés conformément au MDR ?",
    chapter: "Article 29",
    topic: "Enregistrement des dispositifs",
    article: "29",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 30 - Traçabilité
  {
    id: "MDR-ART-30-Q1",
    text: "La traçabilité permet-elle une identification rapide des lots/séries ?",
    chapter: "Article 30",
    topic: "Traçabilité",
    article: "30",
    isoClause: "7.5.3",
    process: "Traçabilité",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 31 - Organismes notifiés
  {
    id: "MDR-ART-31-Q1",
    text: "Comment avez-vous sélectionné votre organisme notifié ?",
    chapter: "Article 31",
    topic: "Organismes notifiés",
    article: "31",
    isoClause: "7.4.1",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 32 - Organismes notifiés
  {
    id: "MDR-ART-32-Q1",
    text: "Comment vérifiez-vous que l’ON est désigné MDR pour votre périmètre ?",
    chapter: "Article 32",
    topic: "Organismes notifiés",
    article: "32",
    isoClause: "7.4.1",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 33 - Organismes notifiés
  {
    id: "MDR-ART-33-Q1",
    text: "Le numéro d’ON est-il correctement utilisé sur vos documents ?",
    chapter: "Article 33",
    topic: "Organismes notifiés",
    article: "33",
    isoClause: "7.5.1",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 34 - Organismes notifiés
  {
    id: "MDR-ART-34-Q1",
    text: "Comment suivez-vous les évaluations des ON par les autorités ?",
    chapter: "Article 34",
    topic: "Organismes notifiés",
    article: "34",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 35 - Organismes notifiés
  {
    id: "MDR-ART-35-Q1",
    text: "Comment évaluez-vous la robustesse de votre ON ?",
    chapter: "Article 35",
    topic: "Organismes notifiés",
    article: "35",
    isoClause: "7.4.1",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 36 - Organismes notifiés
  {
    id: "MDR-ART-36-Q1",
    text: "Comment êtes-vous informé des modifications de désignation ON ?",
    chapter: "Article 36",
    topic: "Organismes notifiés",
    article: "36",
    isoClause: "7.4.1",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 37 - Organismes notifiés
  {
    id: "MDR-ART-37-Q1",
    text: "Existe-t-il une procédure d’escalade en cas de désaccord ON ?",
    chapter: "Article 37",
    topic: "Organismes notifiés",
    article: "37",
    isoClause: "7.2.3",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 38 - Évaluation de conformité
  {
    id: "MDR-ART-38-Q1",
    text: "La procédure d’évaluation de conformité est-elle documentée ?",
    chapter: "Article 38",
    topic: "Évaluation de conformité",
    article: "38",
    isoClause: "7.1",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 39 - Évaluation de conformité
  {
    id: "MDR-ART-39-Q1",
    text: "Les dossiers soumis à l’ON sont-ils complets et cohérents ?",
    chapter: "Article 39",
    topic: "Évaluation de conformité",
    article: "39",
    isoClause: "7.1",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 40 - Évaluation de conformité
  {
    id: "MDR-ART-40-Q1",
    text: "Les certificats CE MDR sont-ils valides et à jour ?",
    chapter: "Article 40",
    topic: "Évaluation de conformité",
    article: "40",
    isoClause: "7.5.1",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 41 - Évaluation clinique
  {
    id: "MDR-ART-41-Q1",
    text: "Disposez-vous d’une procédure d’évaluation clinique conforme MDR ?",
    chapter: "Article 41",
    topic: "Évaluation clinique",
    article: "41",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 42 - Investigations cliniques
  {
    id: "MDR-ART-42-Q1",
    text: "Dans quels cas une investigation clinique est-elle déclenchée ?",
    chapter: "Article 42",
    topic: "Investigations cliniques",
    article: "42",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 43 - Investigations cliniques
  {
    id: "MDR-ART-43-Q1",
    text: "Comment identifiez-vous les DM utilisés uniquement à des fins cliniques ?",
    chapter: "Article 43",
    topic: "Investigations cliniques",
    article: "43",
    isoClause: "7.5.3",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 44 - Investigations cliniques
  {
    id: "MDR-ART-44-Q1",
    text: "Le consentement éclairé est-il systématiquement recueilli ?",
    chapter: "Article 44",
    topic: "Investigations cliniques",
    article: "44",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 45 - Investigations cliniques
  {
    id: "MDR-ART-45-Q1",
    text: "Les investigations sont-elles notifiées aux autorités compétentes ?",
    chapter: "Article 45",
    topic: "Investigations cliniques",
    article: "45",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 46 - Investigations cliniques
  {
    id: "MDR-ART-46-Q1",
    text: "Comment démontrez-vous l’équivalence réglementaire hors UE ?",
    chapter: "Article 46",
    topic: "Investigations cliniques",
    article: "46",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 47 - Investigations cliniques
  {
    id: "MDR-ART-47-Q1",
    text: "Les rapports cliniques sont-ils complets et signés ?",
    chapter: "Article 47",
    topic: "Investigations cliniques",
    article: "47",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 48 - Investigations cliniques
  {
    id: "MDR-ART-48-Q1",
    text: "Comment intégrez-vous les lignes directrices européennes cliniques ?",
    chapter: "Article 48",
    topic: "Investigations cliniques",
    article: "48",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 49 - PMS
  {
    id: "MDR-ART-49-Q1",
    text: "Disposez-vous d’un plan PMS conforme MDR ?",
    chapter: "Article 49",
    topic: "PMS",
    article: "49",
    isoClause: "8.2.1",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 50 - PMS
  {
    id: "MDR-ART-50-Q1",
    text: "Quels indicateurs PMS sont définis ?",
    chapter: "Article 50",
    topic: "PMS",
    article: "50",
    isoClause: "8.4",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 51 - Vigilance
  {
    id: "MDR-ART-51-Q1",
    text: "Disposez-vous d’une procédure de vigilance conforme MDR ?",
    chapter: "Article 51",
    topic: "Vigilance",
    article: "51",
    isoClause: "8.2.1",
    process: "Vigilance",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 52 - Vigilance
  {
    id: "MDR-ART-52-Q1",
    text: "Les délais de déclaration réglementaires sont-ils maîtrisés ?",
    chapter: "Article 52",
    topic: "Vigilance",
    article: "52",
    isoClause: "8.2.3",
    process: "Vigilance",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 53 - Vigilance
  {
    id: "MDR-ART-53-Q1",
    text: "Chaque incident fait-il l’objet d’une analyse de cause racine ?",
    chapter: "Article 53",
    topic: "Vigilance",
    article: "53",
    isoClause: "8.5.2",
    process: "Vigilance",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 54 - Vigilance
  {
    id: "MDR-ART-54-Q1",
    text: "Quels indicateurs statistiques sont surveillés ?",
    chapter: "Article 54",
    topic: "Vigilance",
    article: "54",
    isoClause: "8.4",
    process: "Vigilance",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 55 - Vigilance
  {
    id: "MDR-ART-55-Q1",
    text: "Comment intégrez-vous les recommandations européennes de vigilance ?",
    chapter: "Article 55",
    topic: "Vigilance",
    article: "55",
    isoClause: "8.2.1",
    process: "Vigilance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 56 - Vigilance
  {
    id: "MDR-ART-56-Q1",
    text: "Le système de vigilance est-il audité périodiquement ?",
    chapter: "Article 56",
    topic: "Vigilance",
    article: "56",
    isoClause: "8.2.2",
    process: "Vigilance",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 57 - Surveillance du marché
  {
    id: "MDR-ART-57-Q1",
    text: "Comment réagissez-vous aux mesures de surveillance des autorités ?",
    chapter: "Article 57",
    topic: "Surveillance du marché",
    article: "57",
    isoClause: "8.2.3",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 58 - Surveillance du marché
  {
    id: "MDR-ART-58-Q1",
    text: "Existe-t-il une procédure de gestion des inspections ?",
    chapter: "Article 58",
    topic: "Surveillance du marché",
    article: "58",
    isoClause: "8.2.2",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 59 - Surveillance du marché
  {
    id: "MDR-ART-59-Q1",
    text: "Existe-t-il un plan de gestion de crise sanitaire ?",
    chapter: "Article 59",
    topic: "Surveillance du marché",
    article: "59",
    isoClause: "8.3.3",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 60 - Surveillance du marché
  {
    id: "MDR-ART-60-Q1",
    text: "Comment anticipez-vous les mesures exceptionnelles ?",
    chapter: "Article 60",
    topic: "Surveillance du marché",
    article: "60",
    isoClause: "8.5.3",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 61 - Évaluation clinique
  {
    id: "MDR-ART-61-Q1",
    text: "L’évaluation clinique est-elle mise à jour en continu ?",
    chapter: "Article 61",
    topic: "Évaluation clinique",
    article: "61",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 62 - Investigations cliniques
  {
    id: "MDR-ART-62-Q1",
    text: "Dans quels cas une nouvelle investigation clinique est-elle requise ?",
    chapter: "Article 62",
    topic: "Investigations cliniques",
    article: "62",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 63 - Investigations cliniques
  {
    id: "MDR-ART-63-Q1",
    text: "Les exigences spécifiques aux implants / classe III sont-elles identifiées ?",
    chapter: "Article 63",
    topic: "Investigations cliniques",
    article: "63",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 64 - Investigations cliniques
  {
    id: "MDR-ART-64-Q1",
    text: "Les dossiers sont-ils complets et conformes ?",
    chapter: "Article 64",
    topic: "Investigations cliniques",
    article: "64",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 65 - Investigations cliniques
  {
    id: "MDR-ART-65-Q1",
    text: "Comment intégrez-vous les retours des autorités compétentes ?",
    chapter: "Article 65",
    topic: "Investigations cliniques",
    article: "65",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 66 - Investigations cliniques
  {
    id: "MDR-ART-66-Q1",
    text: "Existe-t-il une coordination centrale des investigations ?",
    chapter: "Article 66",
    topic: "Investigations cliniques",
    article: "66",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 67 - Investigations cliniques
  {
    id: "MDR-ART-67-Q1",
    text: "Comment sont évaluées les modifications d’investigation ?",
    chapter: "Article 67",
    topic: "Investigations cliniques",
    article: "67",
    isoClause: "7.3.7",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 68 - Investigations cliniques
  {
    id: "MDR-ART-68-Q1",
    text: "Les investigations sont-elles enregistrées conformément au MDR ?",
    chapter: "Article 68",
    topic: "Investigations cliniques",
    article: "68",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 69 - PMS
  {
    id: "MDR-ART-69-Q1",
    text: "Existe-t-il un plan PMS spécifique implant ?",
    chapter: "Article 69",
    topic: "PMS",
    article: "69",
    isoClause: "8.2.1",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 70 - PMS
  {
    id: "MDR-ART-70-Q1",
    text: "Les PSUR sont-ils établis selon la classe du DM ?",
    chapter: "Article 70",
    topic: "PMS",
    article: "70",
    isoClause: "8.2.1",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 71 - Transparence
  {
    id: "MDR-ART-71-Q1",
    text: "Quelles informations MDR sont rendues publiques ?",
    chapter: "Article 71",
    topic: "Transparence",
    article: "71",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 72 - EUDAMED
  {
    id: "MDR-ART-72-Q1",
    text: "Les données cliniques et vigilance sont-elles correctement saisies dans EUDAMED ?",
    chapter: "Article 72",
    topic: "EUDAMED",
    article: "72",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 73 - EUDAMED
  {
    id: "MDR-ART-73-Q1",
    text: "Les certificats CE sont-ils correctement enregistrés ?",
    chapter: "Article 73",
    topic: "EUDAMED",
    article: "73",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 74 - EUDAMED
  {
    id: "MDR-ART-74-Q1",
    text: "Les données PMS transmises sont-elles alignées avec vos rapports internes ?",
    chapter: "Article 74",
    topic: "EUDAMED",
    article: "74",
    isoClause: "8.2.1",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 75 - EUDAMED
  {
    id: "MDR-ART-75-Q1",
    text: "Les investigations sont-elles enregistrées dans EUDAMED ?",
    chapter: "Article 75",
    topic: "EUDAMED",
    article: "75",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 76 - Transparence
  {
    id: "MDR-ART-76-Q1",
    text: "Les SSCP sont-ils établis selon les exigences MDR ?",
    chapter: "Article 76",
    topic: "Transparence",
    article: "76",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 77 - Gouvernance
  {
    id: "MDR-ART-77-Q1",
    text: "Comment prenez-vous en compte les avis des comités d’experts ?",
    chapter: "Article 77",
    topic: "Gouvernance",
    article: "77",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 78 - Évaluation clinique
  {
    id: "MDR-ART-78-Q1",
    text: "Comment préparez-vous les revues cliniques autorités/ON ?",
    chapter: "Article 78",
    topic: "Évaluation clinique",
    article: "78",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 79 - Évaluation clinique
  {
    id: "MDR-ART-79-Q1",
    text: "Comment gérez-vous une évaluation coordonnée multi-pays ?",
    chapter: "Article 79",
    topic: "Évaluation clinique",
    article: "79",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 80 - Gouvernance
  {
    id: "MDR-ART-80-Q1",
    text: "Existe-t-il une veille structurée des décisions Commission UE ?",
    chapter: "Article 80",
    topic: "Gouvernance",
    article: "80",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 81 - Sanctions
  {
    id: "MDR-ART-81-Q1",
    text: "Les sanctions nationales applicables sont-elles identifiées ?",
    chapter: "Article 81",
    topic: "Sanctions",
    article: "81",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 82 - Coopération
  {
    id: "MDR-ART-82-Q1",
    text: "Comment tenez-vous compte des échanges inter-États ?",
    chapter: "Article 82",
    topic: "Coopération",
    article: "82",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 83 - Coopération
  {
    id: "MDR-ART-83-Q1",
    text: "Comment assurez-vous la cohérence des informations transmises ?",
    chapter: "Article 83",
    topic: "Coopération",
    article: "83",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 84 - Non-conformités
  {
    id: "MDR-ART-84-Q1",
    text: "Existe-t-il une procédure de gestion des non-conformités réglementaires ?",
    chapter: "Article 84",
    topic: "Non-conformités",
    article: "84",
    isoClause: "8.3",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 85 - Non-conformités
  {
    id: "MDR-ART-85-Q1",
    text: "Comment évaluez-vous la gravité réglementaire d’une non-conformité ?",
    chapter: "Article 85",
    topic: "Non-conformités",
    article: "85",
    isoClause: "8.3",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 86 - Mesures restrictives
  {
    id: "MDR-ART-86-Q1",
    text: "Comment appliquez-vous une restriction de mise sur le marché ?",
    chapter: "Article 86",
    topic: "Mesures restrictives",
    article: "86",
    isoClause: "8.3.3",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 87 - Vigilance
  {
    id: "MDR-ART-87-Q1",
    text: "Comment identifiez-vous une tendance significative ?",
    chapter: "Article 87",
    topic: "Vigilance",
    article: "87",
    isoClause: "8.4",
    process: "Vigilance",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 88 - Vigilance
  {
    id: "MDR-ART-88-Q1",
    text: "Comment les données vigilance sont-elles analysées globalement ?",
    chapter: "Article 88",
    topic: "Vigilance",
    article: "88",
    isoClause: "8.4",
    process: "Vigilance",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 89 - Mesures d'urgence
  {
    id: "MDR-ART-89-Q1",
    text: "Existe-t-il un plan d’urgence sanitaire ?",
    chapter: "Article 89",
    topic: "Mesures d'urgence",
    article: "89",
    isoClause: "8.3.3",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 90 - Suivi
  {
    id: "MDR-ART-90-Q1",
    text: "Comment assurez-vous le suivi des mesures imposées ?",
    chapter: "Article 90",
    topic: "Suivi",
    article: "90",
    isoClause: "8.2.3",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 91 - Actes délégués
  {
    id: "MDR-ART-91-Q1",
    text: "Disposez-vous d’une veille sur les actes délégués MDR ?",
    chapter: "Article 91",
    topic: "Actes délégués",
    article: "91",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 92 - Actes délégués
  {
    id: "MDR-ART-92-Q1",
    text: "Comment suivez-vous la validité des délégations ?",
    chapter: "Article 92",
    topic: "Actes délégués",
    article: "92",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 93 - Gouvernance
  {
    id: "MDR-ART-93-Q1",
    text: "Comment tenez-vous compte des résultats des comités européens ?",
    chapter: "Article 93",
    topic: "Gouvernance",
    article: "93",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 94 - Gouvernance
  {
    id: "MDR-ART-94-Q1",
    text: "Comment suivez-vous les actes d’exécution ?",
    chapter: "Article 94",
    topic: "Gouvernance",
    article: "94",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 95 - Gouvernance
  {
    id: "MDR-ART-95-Q1",
    text: "Les rapports annuels UE sont-ils analysés ?",
    chapter: "Article 95",
    topic: "Gouvernance",
    article: "95",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 96 - Gouvernance
  {
    id: "MDR-ART-96-Q1",
    text: "Comment anticipez-vous les coûts réglementaires futurs ?",
    chapter: "Article 96",
    topic: "Gouvernance",
    article: "96",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 97 - Dispositions transitoires
  {
    id: "MDR-ART-97-Q1",
    text: "Les dispositifs bénéficiant de mesures transitoires sont-ils identifiés ?",
    chapter: "Article 97",
    topic: "Dispositions transitoires",
    article: "97",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 98 - Dispositions transitoires
  {
    id: "MDR-ART-98-Q1",
    text: "Comment assurez-vous la conformité aux dates d’application MDR ?",
    chapter: "Article 98",
    topic: "Dispositions transitoires",
    article: "98",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 99 - Gouvernance
  {
    id: "MDR-ART-99-Q1",
    text: "Comment identifiez-vous les textes abrogés ?",
    chapter: "Article 99",
    topic: "Gouvernance",
    article: "99",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 100 - Gouvernance
  {
    id: "MDR-ART-100-Q1",
    text: "Comment identifiez-vous les parties prenantes réglementaires ?",
    chapter: "Article 100",
    topic: "Gouvernance",
    article: "100",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 101 - Gouvernance
  {
    id: "MDR-ART-101-Q1",
    text: "Comment identifiez-vous et suivez-vous les guidelines MDCG applicables à vos DM ?",
    chapter: "Article 101",
    topic: "Gouvernance",
    article: "101",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 102 - Gouvernance
  {
    id: "MDR-ART-102-Q1",
    text: "Comment assurez-vous la prise en compte rapide des nouvelles orientations MDCG ?",
    chapter: "Article 102",
    topic: "Gouvernance",
    article: "102",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 103 - Gouvernance
  {
    id: "MDR-ART-103-Q1",
    text: "Comment tenez-vous compte des avis des comités d’experts ?",
    chapter: "Article 103",
    topic: "Gouvernance",
    article: "103",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 104 - Gouvernance
  {
    id: "MDR-ART-104-Q1",
    text: "Vos DM sont-ils soumis à des essais par des laboratoires de référence UE ?",
    chapter: "Article 104",
    topic: "Gouvernance",
    article: "104",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 105 - Gouvernance
  {
    id: "MDR-ART-105-Q1",
    text: "Les laboratoires utilisés sont-ils qualifiés et compétents ?",
    chapter: "Article 105",
    topic: "Gouvernance",
    article: "105",
    isoClause: "7.4.1",
    process: "Achats",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 106 - Gouvernance
  {
    id: "MDR-ART-106-Q1",
    text: "Comment prenez-vous en compte les orientations issues des conférences autorités ?",
    chapter: "Article 106",
    topic: "Gouvernance",
    article: "106",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 107 - Gouvernance
  {
    id: "MDR-ART-107-Q1",
    text: "Comment garantissez-vous la fiabilité des données échangées électroniquement ?",
    chapter: "Article 107",
    topic: "Gouvernance",
    article: "107",
    isoClause: "N/A",
    process: "IT",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 108 - Gouvernance
  {
    id: "MDR-ART-108-Q1",
    text: "Comment protégez-vous les informations confidentielles réglementaires ?",
    chapter: "Article 108",
    topic: "Gouvernance",
    article: "108",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 109 - Gouvernance
  {
    id: "MDR-ART-109-Q1",
    text: "Le traitement des données cliniques est-il conforme au RGPD ?",
    chapter: "Article 109",
    topic: "Gouvernance",
    article: "109",
    isoClause: "N/A",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Article 110 - Gouvernance
  {
    id: "MDR-ART-110-Q1",
    text: "Les redevances réglementaires sont-elles identifiées et budgétées ?",
    chapter: "Article 110",
    topic: "Gouvernance",
    article: "110",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 111 - Gouvernance
  {
    id: "MDR-ART-111-Q1",
    text: "Comment identifiez-vous les interlocuteurs autorités compétentes par pays ?",
    chapter: "Article 111",
    topic: "Gouvernance",
    article: "111",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 112 - Gouvernance
  {
    id: "MDR-ART-112-Q1",
    text: "Comment prenez-vous en compte les retours d’expérience sur l’application du MDR ?",
    chapter: "Article 112",
    topic: "Gouvernance",
    article: "112",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 113 - Gouvernance
  {
    id: "MDR-ART-113-Q1",
    text: "Comment anticipez-vous les évolutions majeures du MDR ?",
    chapter: "Article 113",
    topic: "Gouvernance",
    article: "113",
    isoClause: "N/A",
    process: "Gouvernance",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Article 114 - Gouvernance
  {
    id: "MDR-ART-114-Q1",
    text: "Comment assurez-vous la prise en compte des dispositions finales du MDR ?",
    chapter: "Article 114",
    topic: "Gouvernance",
    article: "114",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Article 119 - Gouvernance
  {
    id: "MDR-ART-119-Q1",
    text: "Comment gérez-vous les exigences linguistiques par pays ?",
    chapter: "Article 119",
    topic: "Gouvernance",
    article: "119",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // MDR - Annexe I - GSPR
  {
    id: "MDR-ANNEX-I-Q1",
    text: "Disposez-vous d’une matrice GSPR complète et justifiée point par point ?",
    chapter: "Annexe I",
    topic: "GSPR",
    article: "N/A",
    isoClause: "7.1",
    process: "Conception",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Annexe II - Documentation technique
  {
    id: "MDR-ANNEX-II-Q1",
    text: "La documentation technique est-elle complète et cohérente ?",
    chapter: "Annexe II",
    topic: "Documentation technique",
    article: "N/A",
    isoClause: "4.2.3",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Annexe III - PMS
  {
    id: "MDR-ANNEX-III-Q1",
    text: "Le plan PMS est-il conforme MDR ?",
    chapter: "Annexe III",
    topic: "PMS",
    article: "N/A",
    isoClause: "8.2.1",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Annexe IV - Déclaration de conformité
  {
    id: "MDR-ANNEX-IV-Q1",
    text: "La DoC UE couvre-t-elle toutes les exigences MDR ?",
    chapter: "Annexe IV",
    topic: "Déclaration de conformité",
    article: "N/A",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Annexes V à X - Évaluation de conformité
  {
    id: "MDR-ANNEX-V-X-Q1",
    text: "La voie d’évaluation choisie est-elle justifiée ?",
    chapter: "Annexes V à X",
    topic: "Évaluation de conformité",
    article: "N/A",
    isoClause: "7.1",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Annexe XI - PMS
  {
    id: "MDR-ANNEX-XI-Q1",
    text: "Les PSUR sont-ils conformes à la classe du DM ?",
    chapter: "Annexe XI",
    topic: "PMS",
    article: "N/A",
    isoClause: "8.2.1",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Annexe XII - Certificats
  {
    id: "MDR-ANNEX-XII-Q1",
    text: "Les certificats sont-ils valides, à jour, cohérents ?",
    chapter: "Annexe XII",
    topic: "Certificats",
    article: "N/A",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Annexe XIII - Investigations cliniques
  {
    id: "MDR-ANNEX-XIII-Q1",
    text: "Les investigations respectent-elles ISO 14155 & MDR ?",
    chapter: "Annexe XIII",
    topic: "Investigations cliniques",
    article: "N/A",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Annexe XIV - Évaluation clinique
  {
    id: "MDR-ANNEX-XIV-Q1",
    text: "L’évaluation clinique est-elle vivante ?",
    chapter: "Annexe XIV",
    topic: "Évaluation clinique",
    article: "N/A",
    isoClause: "7.3.6",
    process: "Clinique",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // MDR - Annexe XV - PMCF
  {
    id: "MDR-ANNEX-XV-Q1",
    text: "Le PMCF est-il effectivement mis en œuvre ?",
    chapter: "Annexe XV",
    topic: "PMCF",
    article: "N/A",
    isoClause: "8.2.1",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Annexe XVI - DM sans finalité médicale
  {
    id: "MDR-ANNEX-XVI-Q1",
    text: "Les exigences spécifiques sont-elles appliquées ?",
    chapter: "Annexe XVI",
    topic: "DM sans finalité médicale",
    article: "N/A",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // MDR - Annexe XVII - Table de correspondance
  {
    id: "MDR-ANNEX-XVII-Q1",
    text: "Disposez-vous d’une table de correspondance MDR complète ?",
    chapter: "Annexe XVII",
    topic: "Table de correspondance",
    article: "N/A",
    isoClause: "N/A",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // ISO 13485 - Clause 6 - Gestion des ressources
  {
    id: "ISO-CLAUSE-6-Q1",
    text: "Les ressources humaines sont-elles adéquates et compétentes ?",
    chapter: "Clause 6",
    topic: "Gestion des ressources",
    article: "N/A",
    isoClause: "6.2",
    process: "Ressources humaines",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-6-Q2",
    text: "Les infrastructures sont-elles adaptées et maintenues ?",
    chapter: "Clause 6",
    topic: "Gestion des ressources",
    article: "N/A",
    isoClause: "6.3",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "medium",
  },
  {
    id: "ISO-CLAUSE-6-Q3",
    text: "L’environnement de travail est-il maîtrisé ?",
    chapter: "Clause 6",
    topic: "Gestion des ressources",
    article: "N/A",
    isoClause: "6.4",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "medium",
  },

  // ISO 13485 - Clause 7 - Réalisation du produit
  {
    id: "ISO-CLAUSE-7-Q1",
    text: "La planification de la réalisation du produit est-elle documentée ?",
    chapter: "Clause 7",
    topic: "Réalisation du produit",
    article: "N/A",
    isoClause: "7.1",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-7-Q2",
    text: "Les exigences relatives au produit sont-elles définies ?",
    chapter: "Clause 7",
    topic: "Réalisation du produit",
    article: "N/A",
    isoClause: "7.2.1",
    process: "Conception",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-7-Q3",
    text: "La communication avec le client est-elle efficace ?",
    chapter: "Clause 7",
    topic: "Réalisation du produit",
    article: "N/A",
    isoClause: "7.2.3",
    process: "Commercial",
    economicRole: "Fabricant",
    criticality: "medium",
  },
  {
    id: "ISO-CLAUSE-7-Q4",
    text: "Le processus de conception et développement est-il maîtrisé ?",
    chapter: "Clause 7",
    topic: "Réalisation du produit",
    article: "N/A",
    isoClause: "7.3",
    process: "Conception",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "ISO-CLAUSE-7-Q5",
    text: "Les achats sont-ils conformes aux exigences ?",
    chapter: "Clause 7",
    topic: "Réalisation du produit",
    article: "N/A",
    isoClause: "7.4",
    process: "Achats",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-7-Q6",
    text: "La production et la prestation de services sont-elles maîtrisées ?",
    chapter: "Clause 7",
    topic: "Réalisation du produit",
    article: "N/A",
    isoClause: "7.5",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "ISO-CLAUSE-7-Q7",
    text: "La maîtrise des équipements de surveillance et de mesure est-elle assurée ?",
    chapter: "Clause 7",
    topic: "Réalisation du produit",
    article: "N/A",
    isoClause: "7.6",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // ISO 13485 - Clause 8 - Mesure, analyse et amélioration
  {
    id: "ISO-CLAUSE-8-Q1",
    text: "Les processus de mesure, analyse et amélioration sont-ils établis ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.1",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-8-Q2",
    text: "La rétroaction est-elle collectée et analysée ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.2.1",
    process: "PMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "ISO-CLAUSE-8-Q3",
    text: "Les réclamations sont-elles traitées efficacement ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.2.2",
    process: "Vigilance",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "ISO-CLAUSE-8-Q4",
    text: "Les rapports aux autorités réglementaires sont-ils conformes ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.2.3",
    process: "RA",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "ISO-CLAUSE-8-Q5",
    text: "L’audit interne est-il réalisé périodiquement ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.2.4",
    process: "Audits & conformité",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-8-Q6",
    text: "La surveillance et la mesure des processus sont-elles efficaces ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.2.5",
    process: "Pilotage des processus",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-8-Q7",
    text: "La surveillance et la mesure du produit sont-elles assurées ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.2.6",
    process: "Production",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-8-Q8",
    text: "Les produits non conformes sont-ils maîtrisés ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.3",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "ISO-CLAUSE-8-Q9",
    text: "L’analyse des données est-elle utilisée pour l’amélioration ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.4",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "high",
  },
  {
    id: "ISO-CLAUSE-8-Q10",
    text: "Les actions correctives sont-elles efficaces ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.5.2",
    process: "CAPA",
    economicRole: "Fabricant",
    criticality: "critical",
  },
  {
    id: "ISO-CLAUSE-8-Q11",
    text: "Les actions préventives sont-elles efficaces ?",
    chapter: "Clause 8",
    topic: "Mesure, analyse et amélioration",
    article: "N/A",
    isoClause: "8.5.3",
    process: "CAPA",
    economicRole: "Fabricant",
    criticality: "critical",
  },

  // ISO 13485 - Clause 9 - Amélioration
  {
    id: "ISO-CLAUSE-9-Q1",
    text: "Le processus d’amélioration continue est-il établi ?",
    chapter: "Clause 9",
    topic: "Amélioration",
    article: "N/A",
    isoClause: "8.5",
    process: "QMS",
    economicRole: "Fabricant",
    criticality: "high",
  },

  // ISO 13485 - Clause 10 - Amélioration
  {
    id: "ISO-CLAUSE-10-Q1",
    text: "Les actions correctives et préventives sont-elles efficaces ?",
    chapter: "Clause 10",
    topic: "Amélioration",
    article: "N/A",
    isoClause: "8.5.2",
    process: "CAPA",
    economicRole: "Fabricant",
    criticality: "critical",
  },
];
