import { MdrQuestion } from './mdr-validator';

export const FALLBACK_REFERENTIALS = [
  { code: 'MDR', name: 'Règlement (UE) 2017/745 (MDR)', description: 'Règlement relatif aux dispositifs médicaux', version: '2017/745' },
  { code: 'ISO_13485', name: 'ISO 13485:2016', description: 'Dispositifs médicaux - Systèmes de management de la qualité', version: '2016' },
  { code: 'FDA_820', name: 'FDA 21 CFR Part 820 (QSR)', description: 'Quality System Regulation', version: 'Part 820' }
];

export const FALLBACK_PROCESSES = [
  { id: "gov_strat", name: "Gouvernance & stratégie réglementaire", description: "Pilotage et stratégie", displayOrder: 1, icon: "LayoutDashboard" },
  { id: "ra", name: "Affaires réglementaires (RA)", description: "Conformité et enregistrements", displayOrder: 2, icon: "FileText" },
  { id: "qms", name: "Système de management qualité (QMS)", description: "Maîtrise du SMQ", displayOrder: 3, icon: "ClipboardCheck" },
  { id: "risk_mgmt", name: "Gestion des risques (ISO 14971)", description: "Analyse des risques", displayOrder: 4, icon: "AlertTriangle" },
  { id: "design_dev", name: "Conception & développement", description: "R&D et validation", displayOrder: 5, icon: "Lightbulb" },
  { id: "purchasing_suppliers", name: "Achats & fournisseurs", description: "Maîtrise des approvisionnements", displayOrder: 6, icon: "ShoppingCart" },
  { id: "production_sub", name: "Production & sous-traitance", description: "Fabrication et opérations", displayOrder: 7, icon: "Factory" },
  { id: "traceability_udi", name: "Traçabilité & UDI", description: "Identification et suivi", displayOrder: 8, icon: "Barcode" },
  { id: "pms_pmcf", name: "PMS / PMCF", description: "Surveillance après-vente", displayOrder: 9, icon: "Activity" },
  { id: "vigilance_incidents", name: "Vigilance & incidents", description: "Gestion des événements indésirables", displayOrder: 10, icon: "Bell" },
  { id: "distribution_logistics", name: "Distribution & logistique", description: "Stockage et expédition", displayOrder: 11, icon: "Truck" },
  { id: "importation", name: "Importation", description: "Maîtrise des flux import", displayOrder: 12, icon: "Globe" },
  { id: "tech_doc", name: "Documentation technique", description: "Dossiers techniques DM", displayOrder: 13, icon: "BookOpen" },
  { id: "audits_compliance", name: "Audits & conformité", description: "Vérifications et inspections", displayOrder: 14, icon: "Search" },
  { id: "it_data_cyber", name: "IT / données / cybersécurité (si applicable)", description: "Sécurité des systèmes", displayOrder: 15, icon: "Shield" }
];

// CRITICAL: Every question MUST have an ID and economicRole (never undefined)
export const FALLBACK_MDR_QUESTIONS: MdrQuestion[] = [
  // MDR Article 1
  {
    id: 'MDR-ART1-Q1',
    text: 'Comment avez-vous déterminé que vos produits relèvent du champ MDR ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra'],
    referential: 'MDR',
    article: '1',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART1-Q2',
    text: 'Disposez-vous d’une justification écrite de qualification réglementaire ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra'],
    referential: 'MDR',
    article: '1',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART1-Q3',
    text: 'Comment traitez-vous les produits frontières (logiciel, accessoire, service associé) ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra'],
    referential: 'MDR',
    article: '1',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART1-Q4',
    text: 'Qui valide formellement la qualification DM ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra'],
    referential: 'MDR',
    article: '1',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART1-Q5',
    text: 'Comment assurez-vous une veille réglementaire sur l’évolution du champ MDR ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra'],
    referential: 'MDR',
    article: '1',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 2
  {
    id: 'MDR-ART2-Q1',
    text: 'Où sont formalisées les définitions réglementaires clés ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'ra'],
    referential: 'MDR',
    article: '2',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART2-Q2',
    text: 'Comment assurez-vous l’alignement du vocabulaire interne avec le MDR ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'ra'],
    referential: 'MDR',
    article: '2',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART2-Q3',
    text: 'Les formations internes couvrent-elles les termes critiques MDR ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'ra'],
    referential: 'MDR',
    article: '2',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART2-Q4',
    text: 'Comment évitez-vous les interprétations divergentes entre services ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'ra'],
    referential: 'MDR',
    article: '2',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 3
  {
    id: 'MDR-ART3-Q1',
    text: 'Comment tenez-vous compte des positions et lignes directrices européennes ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat'],
    referential: 'MDR',
    article: '3',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART3-Q2',
    text: 'Avez-vous identifié les documents MDCG applicables ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat'],
    referential: 'MDR',
    article: '3',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART3-Q3',
    text: 'Comment les positions du MDCG sont-elles intégrées dans votre QMS ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'qms'],
    referential: 'MDR',
    article: '3',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 4
  {
    id: 'MDR-ART4-Q1',
    text: 'Disposez-vous d’une procédure d’évaluation de changement réglementaire ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'design_dev'],
    referential: 'MDR',
    article: '4',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART4-Q2',
    text: 'Comment identifiez-vous un changement impactant le statut DM ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'design_dev'],
    referential: 'MDR',
    article: '4',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART4-Q3',
    text: 'Qui valide la requalification réglementaire ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'design_dev'],
    referential: 'MDR',
    article: '4',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART4-Q4',
    text: 'Comment est tracée la décision réglementaire ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'design_dev'],
    referential: 'MDR',
    article: '4',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 5
  {
    id: 'MDR-ART5-Q1',
    text: 'Comment garantissez-vous que seuls des DM conformes MDR sont mis sur le marché ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms', 'production_sub'],
    referential: 'MDR',
    article: '5',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART5-Q2',
    text: 'Quelle preuve démontre la conformité avant première mise sur le marché ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms', 'production_sub'],
    referential: 'MDR',
    article: '5',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART5-Q3',
    text: 'Comment gérez-vous les différences mise sur le marché / mise en service ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms', 'production_sub'],
    referential: 'MDR',
    article: '5',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART5-Q4',
    text: 'Existe-t-il un go/no-go réglementaire formalisé ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms', 'production_sub'],
    referential: 'MDR',
    article: '5',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 6
  {
    id: 'MDR-ART6-Q1',
    text: 'Comment garantissez-vous la conformité MDR des ventes en ligne ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['distribution_logistics', 'marketing'],
    referential: 'MDR',
    article: '6',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART6-Q2',
    text: 'Les informations obligatoires sont-elles accessibles avant achat ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['distribution_logistics', 'marketing'],
    referential: 'MDR',
    article: '6',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART6-Q3',
    text: 'Comment assurez-vous la traçabilité des ventes à distance ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['distribution_logistics', 'marketing'],
    referential: 'MDR',
    article: '6',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART6-Q4',
    text: 'Existe-t-il une revue réglementaire du contenu web ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['distribution_logistics', 'marketing'],
    referential: 'MDR',
    article: '6',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 7
  {
    id: 'MDR-ART7-Q1',
    text: 'Comment validez-vous les allégations cliniques et performances ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['marketing', 'ra'],
    referential: 'MDR',
    article: '7',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART7-Q2',
    text: 'Existe-t-il une revue réglementaire du marketing ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['marketing', 'ra'],
    referential: 'MDR',
    article: '7',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART7-Q3',
    text: 'Comment évitez-vous toute allégation trompeuse ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['marketing', 'ra'],
    referential: 'MDR',
    article: '7',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART7-Q4',
    text: 'Comment sont gérées les communications commerciales internationales ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['marketing', 'ra'],
    referential: 'MDR',
    article: '7',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 8
  {
    id: 'MDR-ART8-Q1',
    text: 'Quelles normes harmonisées appliquez-vous ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms'],
    referential: 'MDR',
    article: '8',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART8-Q2',
    text: 'Comment assurez-vous leur mise à jour ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms'],
    referential: 'MDR',
    article: '8',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART8-Q3',
    text: 'Comment traitez-vous les écarts à une norme harmonisée ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms'],
    referential: 'MDR',
    article: '8',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART8-Q4',
    text: 'Où est documentée la présomption de conformité ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms'],
    referential: 'MDR',
    article: '8',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 9
  {
    id: 'MDR-ART9-Q1',
    text: 'Avez-vous identifié des CS applicables ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms'],
    referential: 'MDR',
    article: '9',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART9-Q2',
    text: 'Comment démontrez-vous leur prise en compte complète ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms'],
    referential: 'MDR',
    article: '9',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART9-Q3',
    text: 'Comment gérez-vous une CS nouvelle ou modifiée ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms'],
    referential: 'MDR',
    article: '9',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 10
  {
    id: 'MDR-ART10-Q1',
    text: 'Votre QMS couvre-t-il l’intégralité des exigences MDR ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'ra', 'pms_pmcf', 'risk_mgmt'],
    referential: 'MDR',
    article: '10',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART10-Q2',
    text: 'Comment démontrez-vous la conformité sur tout le cycle de vie ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'ra', 'pms_pmcf', 'risk_mgmt'],
    referential: 'MDR',
    article: '10',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART10-Q3',
    text: 'Comment est intégrée la gestion des risques ISO 14971 ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'risk_mgmt'],
    referential: 'MDR',
    article: '10',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART10-Q4',
    text: 'Comment est structurée la PMS / PMCF ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['pms_pmcf'],
    referential: 'MDR',
    article: '10',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART10-Q5',
    text: 'Qui est responsable de la conformité réglementaire globale ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra'],
    referential: 'MDR',
    article: '10',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART10-Q6',
    text: 'Comment traitez-vous les non-conformités réglementaires ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'ra'],
    referential: 'MDR',
    article: '10',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART10-Q7',
    text: 'Existe-t-il une revue périodique de conformité MDR ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'ra'],
    referential: 'MDR',
    article: '10',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 11
  {
    id: 'MDR-ART11-Q1',
    text: 'Le fabricant hors UE a-t-il désigné un mandataire MDR unique ?',
    criticality: 'critical',
    economicRole: 'mandataire',
    applicableProcesses: ['ra', 'gov_strat'],
    referential: 'MDR',
    article: '11',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART11-Q2',
    text: 'Le mandat écrit couvre-t-il l’intégralité des responsabilités exigées par l’article 11 ?',
    criticality: 'critical',
    economicRole: 'mandataire',
    applicableProcesses: ['ra', 'gov_strat'],
    referential: 'MDR',
    article: '11',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART11-Q3',
    text: 'Comment le mandataire est-il impliqué dans la vigilance et la PMS ?',
    criticality: 'high',
    economicRole: 'mandataire',
    applicableProcesses: ['ra', 'pms_pmcf', 'vigilance_incidents'],
    referential: 'MDR',
    article: '11',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART11-Q4',
    text: 'Comment sont gérés les changements de mandataire ?',
    criticality: 'critical',
    economicRole: 'mandataire',
    applicableProcesses: ['ra', 'gov_strat'],
    referential: 'MDR',
    article: '11',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART11-Q5',
    text: 'Comment assurez-vous la communication efficace fabricant ↔ mandataire ?',
    criticality: 'high',
    economicRole: 'mandataire',
    applicableProcesses: ['ra', 'gov_strat'],
    referential: 'MDR',
    article: '11',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 12
  {
    id: 'MDR-ART12-Q1',
    text: 'Comment identifiez-vous les exigences nationales additionnelles ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '12',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART12-Q2',
    text: 'Existe-t-il une veille réglementaire pays par pays ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '12',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART12-Q3',
    text: 'Comment ces exigences sont-elles intégrées dans le QMS ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms'],
    referential: 'MDR',
    article: '12',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART12-Q4',
    text: 'Qui valide la conformité locale avant commercialisation ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '12',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 13
  {
    id: 'MDR-ART13-Q1',
    text: 'Comment l’importateur vérifie-t-il la conformité MDR avant mise sur le marché ?',
    criticality: 'critical',
    economicRole: 'importateur',
    applicableProcesses: ['importation', 'purchasing_suppliers'],
    referential: 'MDR',
    article: '13',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART13-Q2',
    text: 'Dispose-t-il d’une procédure de contrôle documentaire ?',
    criticality: 'high',
    economicRole: 'importateur',
    applicableProcesses: ['importation', 'purchasing_suppliers'],
    referential: 'MDR',
    article: '13',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART13-Q3',
    text: 'Comment est vérifiée la présence du marquage CE et UDI ?',
    criticality: 'critical',
    economicRole: 'importateur',
    applicableProcesses: ['importation', 'traceability_udi'],
    referential: 'MDR',
    article: '13',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART13-Q4',
    text: 'Comment sont gérés les DM non conformes ?',
    criticality: 'critical',
    economicRole: 'importateur',
    applicableProcesses: ['importation', 'qms'],
    referential: 'MDR',
    article: '13',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART13-Q5',
    text: 'Comment l’importateur contribue-t-il à la traçabilité et à la vigilance ?',
    criticality: 'high',
    economicRole: 'importateur',
    applicableProcesses: ['importation', 'traceability_udi', 'vigilance_incidents'],
    referential: 'MDR',
    article: '13',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 14
  {
    id: 'MDR-ART14-Q1',
    text: 'Comment le distributeur vérifie-t-il la conformité des DM reçus ?',
    criticality: 'critical',
    economicRole: 'distributeur',
    applicableProcesses: ['distribution_logistics'],
    referential: 'MDR',
    article: '14',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART14-Q2',
    text: 'Existe-t-il une checklist de conformité MDR à réception ?',
    criticality: 'high',
    economicRole: 'distributeur',
    applicableProcesses: ['distribution_logistics'],
    referential: 'MDR',
    article: '14',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART14-Q3',
    text: 'Comment sont gérés les DM suspects ou non conformes ?',
    criticality: 'critical',
    economicRole: 'distributeur',
    applicableProcesses: ['distribution_logistics', 'qms'],
    referential: 'MDR',
    article: '14',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART14-Q4',
    text: 'Comment le distributeur contribue-t-il à la traçabilité aval ?',
    criticality: 'high',
    economicRole: 'distributeur',
    applicableProcesses: ['distribution_logistics', 'traceability_udi'],
    referential: 'MDR',
    article: '14',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART14-Q5',
    text: 'Comment est assurée la remontée d’information vers le fabricant ?',
    criticality: 'critical',
    economicRole: 'distributeur',
    applicableProcesses: ['distribution_logistics', 'vigilance_incidents'],
    referential: 'MDR',
    article: '14',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 15
  {
    id: 'MDR-ART15-Q1',
    text: 'Une PRRC est-elle formellement désignée ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra'],
    referential: 'MDR',
    article: '15',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART15-Q2',
    text: 'Les compétences réglementaires sont-elles démontrées ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra'],
    referential: 'MDR',
    article: '15',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART15-Q3',
    text: 'La PRRC a-t-elle une autorité réelle dans l’organisation ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra'],
    referential: 'MDR',
    article: '15',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART15-Q4',
    text: 'Comment est assurée la continuité en cas d’absence ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra'],
    referential: 'MDR',
    article: '15',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART15-Q5',
    text: 'La PRRC est-elle impliquée dans libération produit, PMS, vigilance ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'ra', 'pms_pmcf', 'vigilance_incidents'],
    referential: 'MDR',
    article: '15',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 16
  {
    id: 'MDR-ART16-Q1',
    text: 'Comment identifiez-vous un changement entraînant une requalification fabricant ?',
    criticality: 'critical',
    economicRole: 'importateur',
    applicableProcesses: ['ra', 'design_dev'],
    referential: 'MDR',
    article: '16',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART16-Q2',
    text: 'Existe-t-il une procédure de gestion des modifications ?',
    criticality: 'high',
    economicRole: 'importateur',
    applicableProcesses: ['ra', 'design_dev'],
    referential: 'MDR',
    article: '16',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART16-Q3',
    text: 'Comment est documentée la décision réglementaire ?',
    criticality: 'critical',
    economicRole: 'importateur',
    applicableProcesses: ['ra', 'design_dev'],
    referential: 'MDR',
    article: '16',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART16-Q4',
    text: 'Qui valide le nouveau rôle réglementaire ?',
    criticality: 'critical',
    economicRole: 'importateur',
    applicableProcesses: ['ra', 'design_dev'],
    referential: 'MDR',
    article: '16',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART16-Q5',
    text: 'Comment sont gérées les responsabilités MDR associées ?',
    criticality: 'high',
    economicRole: 'importateur',
    applicableProcesses: ['ra', 'design_dev'],
    referential: 'MDR',
    article: '16',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 17
  {
    id: 'MDR-ART17-Q1',
    text: 'Les dispositifs remis à neuf sont-ils explicitement couverts par le QMS ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'qms'],
    referential: 'MDR',
    article: '17',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART17-Q2',
    text: 'Comment démontrez-vous la sécurité et performance après reconditionnement ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'qms'],
    referential: 'MDR',
    article: '17',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART17-Q3',
    text: 'Comment est assurée la traçabilité des opérations ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'traceability_udi'],
    referential: 'MDR',
    article: '17',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART17-Q4',
    text: 'Existe-t-il une évaluation de risque spécifique ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'risk_mgmt'],
    referential: 'MDR',
    article: '17',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART17-Q5',
    text: 'Comment informez-vous les utilisateurs finaux ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'marketing'],
    referential: 'MDR',
    article: '17',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 18
  {
    id: 'MDR-ART18-Q1',
    text: 'Les cartes implant sont-elles conformes au MDR ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'pms_pmcf'],
    referential: 'MDR',
    article: '18',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART18-Q2',
    text: 'Comment assurez-vous la complétude et la lisibilité des informations patient ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'pms_pmcf'],
    referential: 'MDR',
    article: '18',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART18-Q3',
    text: 'Comment gérez-vous les mises à jour d’information ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'pms_pmcf'],
    referential: 'MDR',
    article: '18',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART18-Q4',
    text: 'Existe-t-il une validation réglementaire des supports patient ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'pms_pmcf'],
    referential: 'MDR',
    article: '18',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 19
  {
    id: 'MDR-ART19-Q1',
    text: 'La DoC UE couvre-t-elle toutes les exigences MDR applicables ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '19',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART19-Q2',
    text: 'Est-elle signée par une personne autorisée ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '19',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART19-Q3',
    text: 'Comment est assurée la mise à jour de la DoC ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '19',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART19-Q4',
    text: 'Où est tracée la cohérence DoC ↔ documentation technique ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'tech_doc'],
    referential: 'MDR',
    article: '19',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART19-Q5',
    text: 'La DoC est-elle mise à disposition sur demande ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '19',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 20
  {
    id: 'MDR-ART20-Q1',
    text: 'Comment garantissez-vous que le marquage CE est apposé correctement ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'production_sub'],
    referential: 'MDR',
    article: '20',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART20-Q2',
    text: 'Comment est vérifiée la cohérence CE ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'production_sub'],
    referential: 'MDR',
    article: '20',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 21
  {
    id: 'MDR-ART21-Q1',
    text: 'Comment garantissez-vous la libre circulation des DM conformes MDR dans l’UE ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'distribution_logistics'],
    referential: 'MDR',
    article: '21',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART21-Q2',
    text: 'Comment traitez-vous les restrictions nationales éventuelles ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'distribution_logistics'],
    referential: 'MDR',
    article: '21',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART21-Q3',
    text: 'Existe-t-il une traçabilité des décisions de restriction ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'distribution_logistics'],
    referential: 'MDR',
    article: '21',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART21-Q4',
    text: 'Comment informez-vous les partenaires aval ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'distribution_logistics'],
    referential: 'MDR',
    article: '21',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 22
  {
    id: 'MDR-ART22-Q1',
    text: 'Comment intégrez-vous les orientations européennes en matière de PMS/vigilance ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['pms_pmcf', 'vigilance_incidents', 'ra'],
    referential: 'MDR',
    article: '22',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART22-Q2',
    text: 'Les documents MDCG sont-ils analysés et applicables ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['pms_pmcf', 'vigilance_incidents', 'ra'],
    referential: 'MDR',
    article: '22',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART22-Q3',
    text: 'Comment ces orientations sont-elles déployées dans le QMS ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['pms_pmcf', 'vigilance_incidents', 'ra', 'qms'],
    referential: 'MDR',
    article: '22',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 23
  {
    id: 'MDR-ART23-Q1',
    text: 'Existe-t-il une veille sur les décisions de la Commission européenne ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '23',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART23-Q2',
    text: 'Comment ces décisions sont-elles évaluées et intégrées ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '23',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART23-Q3',
    text: 'Qui est responsable de la mise à jour du QMS suite aux décisions UE ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'qms'],
    referential: 'MDR',
    article: '23',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 24
  {
    id: 'MDR-ART24-Q1',
    text: 'Disposez-vous d’une procédure UDI documentée ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['traceability_udi', 'production_sub', 'ra'],
    referential: 'MDR',
    article: '24',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART24-Q2',
    text: 'Comment sont attribués UDI-DI et UDI-PI ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['traceability_udi', 'production_sub', 'ra'],
    referential: 'MDR',
    article: '24',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART24-Q3',
    text: 'Comment garantissez-vous la cohérence UDI ↔ produit ↔ documentation ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['traceability_udi', 'production_sub', 'ra'],
    referential: 'MDR',
    article: '24',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART24-Q4',
    text: 'Comment les partenaires aval vérifient-ils l’UDI ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['traceability_udi', 'distribution_logistics'],
    referential: 'MDR',
    article: '24',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART24-Q5',
    text: 'Comment gérez-vous les erreurs UDI ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['traceability_udi', 'qms'],
    referential: 'MDR',
    article: '24',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 25
  {
    id: 'MDR-ART25-Q1',
    text: 'Comment identifiez-vous les opérateurs économiques dans la chaîne ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['purchasing_suppliers', 'traceability_udi'],
    referential: 'MDR',
    article: '25',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART25-Q2',
    text: 'Comment assurez-vous la traçabilité amont/aval sur 10 ans ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['purchasing_suppliers', 'traceability_udi'],
    referential: 'MDR',
    article: '25',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART25-Q3',
    text: 'Existe-t-il une procédure de rappel produit ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['purchasing_suppliers', 'vigilance_incidents'],
    referential: 'MDR',
    article: '25',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART25-Q4',
    text: 'Comment testez-vous l’efficacité de la traçabilité ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['purchasing_suppliers', 'traceability_udi'],
    referential: 'MDR',
    article: '25',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 26
  {
    id: 'MDR-ART26-Q1',
    text: 'Qui est responsable des enregistrements EUDAMED ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '26',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART26-Q2',
    text: 'Comment assurez-vous l’exactitude des données déclarées ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '26',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART26-Q3',
    text: 'Comment gérez-vous les mises à jour ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '26',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART26-Q4',
    text: 'Existe-t-il un contrôle interne EUDAMED ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '26',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART26-Q5',
    text: 'Comment gérez-vous les défaillances temporaires d’EUDAMED ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['ra'],
    referential: 'MDR',
    article: '26',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 27
  {
    id: 'MDR-ART27-Q1',
    text: 'Comment est intégré l’UDI dans la PMS et la vigilance ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['traceability_udi', 'pms_pmcf', 'vigilance_incidents'],
    referential: 'MDR',
    article: '27',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART27-Q2',
    text: 'Comment assurez-vous la lisibilité de l’UDI sur tout le cycle de vie ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['traceability_udi', 'pms_pmcf', 'vigilance_incidents'],
    referential: 'MDR',
    article: '27',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART27-Q3',
    text: 'Comment gérez-vous l’UDI des dispositifs reconditionnés ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['traceability_udi', 'production_sub'],
    referential: 'MDR',
    article: '27',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART27-Q4',
    text: 'Comment est assurée la formation interne UDI ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['traceability_udi', 'qms'],
    referential: 'MDR',
    article: '27',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 28
  {
    id: 'MDR-ART28-Q1',
    text: 'Tous les opérateurs sont-ils enregistrés et à jour ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'gov_strat'],
    referential: 'MDR',
    article: '28',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART28-Q2',
    text: 'Comment sont gérés les changements d’information ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'gov_strat'],
    referential: 'MDR',
    article: '28',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART28-Q3',
    text: 'Existe-t-il une revue périodique des enregistrements ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'gov_strat'],
    referential: 'MDR',
    article: '28',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 29
  {
    id: 'MDR-ART29-Q1',
    text: 'Tous les dispositifs sont-ils enregistrés conformément au MDR ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'tech_doc'],
    referential: 'MDR',
    article: '29',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART29-Q2',
    text: 'Les données correspondent-elles à la documentation technique ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'tech_doc'],
    referential: 'MDR',
    article: '29',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART29-Q3',
    text: 'Comment sont gérées les variantes et configurations ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'tech_doc'],
    referential: 'MDR',
    article: '29',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'MDR-ART29-Q4',
    text: 'Existe-t-il un contrôle avant mise sur le marché ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['ra', 'tech_doc'],
    referential: 'MDR',
    article: '29',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // MDR Article 30
  {
    id: 'MDR-ART30-Q1',
    text: 'La traçabilité permet-elle une identification rapide des lots/séries ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['traceability_udi', 'pms_pmcf', 'vigilance_incidents'],
    referential: 'MDR',
    article: '30',
    clause: '',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // ISO 13485 Clause 4
  {
    id: 'ISO13485-CL4-Q1',
    text: 'Le périmètre du QMS est-il clairement défini ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'gov_strat'],
    referential: 'ISO 13485',
    article: '',
    clause: '4.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL4-Q2',
    text: 'Les processus sont-ils identifiés, séquencés et maîtrisés ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'gov_strat'],
    referential: 'ISO 13485',
    article: '',
    clause: '4.1.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL4-Q3',
    text: 'Comment sont gérées les exigences réglementaires applicables ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'ra'],
    referential: 'ISO 13485',
    article: '',
    clause: '4.1.2',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL4-Q4',
    text: 'Comment démontrez-vous la maîtrise documentaire ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'tech_doc'],
    referential: 'ISO 13485',
    article: '',
    clause: '4.2.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL4-Q5',
    text: 'Les enregistrements sont-ils traçables, protégés et exploitables ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'tech_doc'],
    referential: 'ISO 13485',
    article: '',
    clause: '4.2.4',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // ISO 13485 Clause 5
  {
    id: 'ISO13485-CL5-Q1',
    text: 'La direction démontre-t-elle son engagement QMS ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '5.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL5-Q2',
    text: 'Les objectifs qualité sont-ils mesurables et suivis ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '5.4.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL5-Q3',
    text: 'La revue de direction couvre-t-elle MDR, risques et performance ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'qms', 'risk_mgmt'],
    referential: 'ISO 13485',
    article: '',
    clause: '5.6',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL5-Q4',
    text: 'Comment les ressources sont-elles allouées ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '5.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL5-Q5',
    text: 'Comment les responsabilités sont-elles définies et communiquées ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '5.5.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // ISO 13485 Clause 6
  {
    id: 'ISO13485-CL6-Q1',
    text: 'Les ressources nécessaires au QMS sont-elles identifiées et planifiées ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q2',
    text: 'Comment démontrez-vous leur adéquation aux exigences réglementaires ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'qms', 'ra'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q3',
    text: 'Comment sont priorisées les ressources critiques MDR ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['gov_strat', 'qms', 'ra'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q4',
    text: 'Les compétences requises sont-elles définies par fonction ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.2',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q5',
    text: 'Comment évaluez-vous l’efficacité des formations ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.2',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q6',
    text: 'Les postes réglementaires clés (PRRC) sont-ils sécurisés ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'ra', 'gov_strat'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.2',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q7',
    text: 'Comment traitez-vous les écarts de compétence ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.2',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q8',
    text: 'Existe-t-il une matrice compétences × risques ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['qms', 'risk_mgmt'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.2',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q9',
    text: 'Les infrastructures sont-elles adaptées aux exigences produit ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.3',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q10',
    text: 'Comment sont gérés les équipements critiques ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.3',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q11',
    text: 'Existe-t-il une maintenance planifiée et tracée ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.3',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q12',
    text: 'Comment gérez-vous les pannes impactant la conformité ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.3',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q13',
    text: 'L’environnement de travail est-il maîtrisé selon les exigences produit ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.4',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q14',
    text: 'Comment gérez-vous les conditions spéciales (propreté, contamination) ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.4',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q15',
    text: 'Existe-t-il une surveillance environnementale ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.4',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL6-Q16',
    text: 'Comment sont traitées les non-conformités environnementales ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['production_sub', 'qms'],
    referential: 'ISO 13485',
    article: '',
    clause: '6.4',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // ISO 13485 Clause 7.1
  {
    id: 'ISO13485-CL7-1-Q1',
    text: 'La planification de la réalisation du produit est-elle documentée ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['design_dev', 'production_sub'],
    referential: 'ISO 13485',
    article: '',
    clause: '7.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL7-1-Q2',
    text: 'Comment les exigences réglementaires sont-elles intégrées dans la planification ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['design_dev', 'production_sub', 'ra'],
    referential: 'ISO 13485',
    article: '',
    clause: '7.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL7-1-Q3',
    text: 'Existe-t-il une revue de planification ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['design_dev', 'production_sub'],
    referential: 'ISO 13485',
    article: '',
    clause: '7.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  // ISO 13485 Clause 7.2
  {
    id: 'ISO13485-CL7-2-Q1',
    text: 'Les exigences relatives au produit sont-elles définies et documentées ?',
    criticality: 'critical',
    economicRole: 'fabricant',
    applicableProcesses: ['design_dev'],
    referential: 'ISO 13485',
    article: '',
    clause: '7.2.1',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL7-2-Q2',
    text: 'Comment les exigences réglementaires sont-elles revues ?',
    criticality: 'high',
    economicRole: 'fabricant',
    applicableProcesses: ['design_dev', 'ra'],
    referential: 'ISO 13485',
    article: '',
    clause: '7.2.2',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
  {
    id: 'ISO13485-CL7-2-Q3',
    text: 'Existe-t-il une procédure de communication avec le client ?',
    criticality: 'medium',
    economicRole: 'fabricant',
    applicableProcesses: ['design_dev', 'marketing'],
    referential: 'ISO 13485',
    article: '',
    clause: '7.2.3',
    guidance: '',
    annex: '',
    chapter: '',
    part: '',
    subpart: '',
    paragraph: '',
    subparagraph: '',
    points: [],
    requirements: [],
    notes: '',
  },
];

export const allProcesses = [
  'Gouvernance & stratégie réglementaire',
  'Affaires réglementaires (RA)',
  'Système de management qualité (QMS)',
  'Gestion des risques (ISO 14971)',
  'Conception & développement',
  'Achats & fournisseurs',
  'Production & sous-traitance',
  'Traçabilité & UDI',
  'PMS / PMCF',
  'Vigilance & incidents',
  'Distribution & logistique',
  'Importation',
  'Documentation technique',
  'Audits & conformité',
  'IT / données / cybersécurité (si applicable)',
];

export const allEconomicRoles = [
  'Fabricant',
  'Mandataire Agréé',
  'Importateur',
  'Distributeur',
];
