/**
 * Fallback data for the QARA platform
 * Fully aligned with the "RAPPORT-AUDIT-COMPLET" and user instructions.
 * Structured to be ultra-tolerant and prevent frontend crashes.
 */

export const FALLBACK_REFERENTIALS = [
  { code: 'MDR', name: 'Règlement (UE) 2017/745 (MDR)', description: 'Règlement relatif aux dispositifs médicaux', version: '2017/745' },
  { code: 'ISO_13485', name: 'ISO 13485:2016', description: 'Dispositifs médicaux - Systèmes de management de la qualité', version: '2016' },
  { code: 'FDA_820', name: 'FDA 21 CFR Part 820 (QSR)', description: 'Quality System Regulation', version: 'Part 820' }
];

export const FALLBACK_PROCESSES = [
  { id: "gov_strat", name: "Gouvernance & stratégie réglementaire", description: "Pilotage et stratégie", displayOrder: 1, icon: "LayoutDashboard" },
  { id: "ra", name: "Affaires réglementaires (RA)", description: "Conformité et enregistrements", displayOrder: 2, icon: "FileText" },
  { id: "qms", name: "Système de management qualité (QMS)", description: "Maîtrise du SMQ", displayOrder: 3, icon: "ClipboardCheck" },
  { id: "risk_mgmt", name: "Gestion des risques (ISO 14971)", description: "Analyse des risques", displayOrder: 4, icon: "AlertTriangle" },
  { id: "design_dev", name: "Conception & développement", description: "R&D et validation", displayOrder: 5, icon: "Lightbulb" },
  { id: "purchasing_suppliers", name: "Achats & fournisseurs", description: "Maîtrise des approvisionnements", displayOrder: 6, icon: "ShoppingCart" },
  { id: "production_sub", name: "Production & sous-traitance", description: "Fabrication et opérations", displayOrder: 7, icon: "Factory" },
  { id: "traceability_udi", name: "Traçabilité & UDI", description: "Identification et suivi", displayOrder: 8, icon: "Barcode" },
  { id: "pms_pmcf", name: "PMS / PMCF", description: "Surveillance après-vente", displayOrder: 9, icon: "Activity" },
  { id: "vigilance_incidents", name: "Vigilance & incidents", description: "Gestion des événements indésirables", displayOrder: 10, icon: "Bell" },
  { id: "distribution_logistics", name: "Distribution & logistique", description: "Stockage et expédition", displayOrder: 11, icon: "Truck" },
  { id: "importation", name: "Importation", description: "Maîtrise des flux import", displayOrder: 12, icon: "Globe" },
  { id: "tech_doc", name: "Documentation technique", description: "Dossiers techniques DM", displayOrder: 13, icon: "BookOpen" },
  { id: "audits_compliance", name: "Audits & conformité", description: "Vérifications et inspections", displayOrder: 14, icon: "Search" },
  { id: "it_data_cyber", name: "IT / données / cybersécurité (si applicable)", description: "Sécurité des systèmes", displayOrder: 15, icon: "Shield" }
];

// CRITICAL: Every question MUST have an ID (string or number)
export const FALLBACK_MDR_QUESTIONS = [
  { 
    id: "mdr-art1-q1", 
    article: "Article 1", 
    questionText: "Comment avez-vous déterminé que vos produits relèvent du champ MDR ?", 
    questionShort: "Qualification du champ d'application",
    criticality: "high", 
    economicRole: "fabricant", 
    processCategory: "Affaires réglementaires (RA)", 
    applicableRoles: ["fabricant"],
    applicableProcesses: ["gov_strat", "ra"],
    displayOrder: 1, 
    isActive: true 
  },
  { 
    id: "mdr-art1-q2", 
    article: "Article 1", 
    questionText: "Disposez-vous d’une justification écrite de qualification réglementaire ?", 
    questionShort: "Justification de qualification",
    criticality: "high", 
    economicRole: "fabricant", 
    processCategory: "Affaires réglementaires (RA)", 
    applicableRoles: ["fabricant"],
    applicableProcesses: ["gov_strat", "ra"],
    displayOrder: 2, 
    isActive: true 
  },
  { 
    id: "mdr-art1-q3", 
    article: "Article 1", 
    questionText: "Comment traitez-vous les produits frontières (logiciel, accessoire, service associé) ?", 
    questionShort: "Produits frontières",
    criticality: "high", 
    economicRole: "fabricant", 
    processCategory: "Affaires réglementaires (RA)", 
    applicableRoles: ["fabricant"],
    applicableProcesses: ["gov_strat", "ra"],
    displayOrder: 3, 
    isActive: true 
  },
  { 
    id: "mdr-art1-q4", 
    article: "Article 1", 
    questionText: "Qui valide formellement la qualification DM ?", 
    questionShort: "Validation qualification DM",
    criticality: "high", 
    economicRole: "fabricant", 
    processCategory: "Affaires réglementaires (RA)", 
    applicableRoles: ["fabricant"],
    applicableProcesses: ["gov_strat", "ra"],
    displayOrder: 4, 
    isActive: true 
  },
  { 
    id: "mdr-art1-q5", 
    article: "Article 1", 
    questionText: "Comment assurez-vous une veille réglementaire sur l’évolution du champ MDR ?", 
    questionShort: "Veille réglementaire",
    criticality: "medium", 
    economicRole: "fabricant", 
    processCategory: "Affaires réglementaires (RA)", 
    applicableRoles: ["fabricant"],
    applicableProcesses: ["gov_strat", "ra"],
    displayOrder: 5, 
    isActive: true 
  },
  {
    id: "mdr-art2-q1",
    article: "Article 2",
    questionText: "Où sont formalisées les définitions réglementaires clés ?",
    questionShort: "Définitions réglementaires",
    criticality: "medium",
    economicRole: "fabricant",
    processCategory: "Gouvernance QMS",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["qms", "tech_doc"],
    displayOrder: 6,
    isActive: true
  },
  {
    id: "mdr-art2-q2",
    article: "Article 2",
    questionText: "Comment assurez-vous l’alignement du vocabulaire interne avec le MDR ?",
    questionShort: "Alignement vocabulaire MDR",
    criticality: "medium",
    economicRole: "fabricant",
    processCategory: "Gouvernance QMS",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["qms", "tech_doc"],
    displayOrder: 7,
    isActive: true
  },
  {
    id: "mdr-art2-q3",
    article: "Article 2",
    questionText: "Les formations internes couvrent-elles les termes critiques MDR ?",
    questionShort: "Formations internes MDR",
    criticality: "medium",
    economicRole: "fabricant",
    processCategory: "Gouvernance QMS",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["qms", "tech_doc"],
    displayOrder: 8,
    isActive: true
  },
  {
    id: "mdr-art2-q4",
    article: "Article 2",
    questionText: "Comment évitez-vous les interprétations divergentes entre services ?",
    questionShort: "Interprétations divergentes",
    criticality: "medium",
    economicRole: "fabricant",
    processCategory: "Gouvernance QMS",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["qms", "tech_doc"],
    displayOrder: 9,
    isActive: true
  },
  {
    id: "mdr-art3-q1",
    article: "Article 3",
    questionText: "Comment tenez-vous compte des positions et lignes directrices européennes ?",
    questionShort: "Positions européennes",
    criticality: "medium",
    economicRole: "fabricant",
    processCategory: "Gouvernance réglementaire",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["gov_strat"],
    displayOrder: 10,
    isActive: true
  },
  {
    id: "mdr-art3-q2",
    article: "Article 3",
    questionText: "Avez-vous identifié les documents MDCG applicables ?",
    questionShort: "Documents MDCG",
    criticality: "medium",
    economicRole: "fabricant",
    processCategory: "Gouvernance réglementaire",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["gov_strat"],
    displayOrder: 11,
    isActive: true
  },
  {
    id: "mdr-art3-q3",
    article: "Article 3",
    questionText: "Comment les positions du MDCG sont-elles intégrées dans votre QMS ?",
    questionShort: "Intégration MDCG au QMS",
    criticality: "medium",
    economicRole: "fabricant",
    processCategory: "Gouvernance réglementaire",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["gov_strat", "qms"],
    displayOrder: 12,
    isActive: true
  },
  {
    id: "mdr-art4-q1",
    article: "Article 4",
    questionText: "Disposez-vous d’une procédure d’évaluation de changement réglementaire ?",
    questionShort: "Procédure de changement réglementaire",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 13,
    isActive: true
  },
  {
    id: "mdr-art4-q2",
    article: "Article 4",
    questionText: "Comment identifiez-vous un changement impactant le statut DM ?",
    questionShort: "Identification changement statut DM",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 14,
    isActive: true
  },
  {
    id: "mdr-art4-q3",
    article: "Article 4",
    questionText: "Qui valide la requalification réglementaire ?",
    questionShort: "Validation requalification",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 15,
    isActive: true
  },
  {
    id: "mdr-art4-q4",
    article: "Article 4",
    questionText: "Comment est tracée la décision réglementaire ?",
    questionShort: "Traçabilité décision réglementaire",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 16,
    isActive: true
  },
  {
    id: "mdr-art5-q1",
    article: "Article 5",
    questionText: "Comment garantissez-vous que seuls des DM conformes MDR sont mis sur le marché ?",
    questionShort: "Conformité avant mise sur le marché",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "qms", "production_sub"],
    displayOrder: 17,
    isActive: true
  },
  {
    id: "mdr-art5-q2",
    article: "Article 5",
    questionText: "Quelle preuve démontre la conformité avant première mise sur le marché ?",
    questionShort: "Preuve de conformité",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "qms", "production_sub"],
    displayOrder: 18,
    isActive: true
  },
  {
    id: "mdr-art5-q3",
    article: "Article 5",
    questionText: "Comment gérez-vous les différences mise sur le marché / mise en service ?",
    questionShort: "Mise sur le marché vs mise en service",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "qms", "production_sub"],
    displayOrder: 19,
    isActive: true
  },
  {
    id: "mdr-art5-q4",
    article: "Article 5",
    questionText: "Existe-t-il un go/no-go réglementaire formalisé ?",
    questionShort: "Go/No-go réglementaire",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "qms", "production_sub"],
    displayOrder: 20,
    isActive: true
  },
  {
    id: "mdr-art6-q1",
    article: "Article 6",
    questionText: "Comment garantissez-vous la conformité MDR des ventes en ligne ?",
    questionShort: "Conformité ventes en ligne",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "Distribution",
    applicableRoles: ["fabricant", "distributeur"],
    applicableProcesses: ["distribution_logistics"],
    displayOrder: 21,
    isActive: true
  },
  {
    id: "mdr-art6-q2",
    article: "Article 6",
    questionText: "Les informations obligatoires sont-elles accessibles avant achat ?",
    questionShort: "Informations pré-achat",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "Distribution",
    applicableRoles: ["fabricant", "distributeur"],
    applicableProcesses: ["distribution_logistics"],
    displayOrder: 22,
    isActive: true
  },
  {
    id: "mdr-art6-q3",
    article: "Article 6",
    questionText: "Comment assurez-vous la traçabilité des ventes à distance ?",
    questionShort: "Traçabilité ventes à distance",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "Distribution",
    applicableRoles: ["fabricant", "distributeur"],
    applicableProcesses: ["distribution_logistics", "traceability_udi"],
    displayOrder: 23,
    isActive: true
  },
  {
    id: "mdr-art6-q4",
    article: "Article 6",
    questionText: "Existe-t-il une revue réglementaire du contenu web ?",
    questionShort: "Revue réglementaire contenu web",
    criticality: "medium",
    economicRole: "fabricant",
    processCategory: "Distribution",
    applicableRoles: ["fabricant", "distributeur"],
    applicableProcesses: ["distribution_logistics"],
    displayOrder: 24,
    isActive: true
  },
  {
    id: "mdr-art7-q1",
    article: "Article 7",
    questionText: "Comment validez-vous les allégations cliniques et performances ?",
    questionShort: "Validation allégations",
    criticality: "critical",
    economicRole: "tous",
    processCategory: "Marketing",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["ra"],
    displayOrder: 25,
    isActive: true
  },
  {
    id: "mdr-art7-q2",
    article: "Article 7",
    questionText: "Existe-t-il une revue réglementaire du marketing ?",
    questionShort: "Revue marketing réglementaire",
    criticality: "high",
    economicRole: "tous",
    processCategory: "Marketing",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["ra"],
    displayOrder: 26,
    isActive: true
  },
  {
    id: "mdr-art7-q3",
    article: "Article 7",
    questionText: "Comment évitez-vous toute allégation trompeuse ?",
    questionShort: "Prévention allégations trompeuses",
    criticality: "high",
    economicRole: "tous",
    processCategory: "Marketing",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["ra"],
    displayOrder: 27,
    isActive: true
  },
  {
    id: "mdr-art7-q4",
    article: "Article 7",
    questionText: "Comment sont gérées les communications commerciales internationales ?",
    questionShort: "Communications commerciales internationales",
    criticality: "medium",
    economicRole: "tous",
    processCategory: "Marketing",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["ra"],
    displayOrder: 28,
    isActive: true
  },
  {
    id: "mdr-art8-q1",
    article: "Article 8",
    questionText: "Quelles normes harmonisées appliquez-vous ?",
    questionShort: "Normes harmonisées appliquées",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra"],
    displayOrder: 29,
    isActive: true
  },
  {
    id: "mdr-art8-q2",
    article: "Article 8",
    questionText: "Comment assurez-vous leur mise à jour ?",
    questionShort: "Mise à jour normes harmonisées",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra"],
    displayOrder: 30,
    isActive: true
  },
  {
    id: "mdr-art8-q3",
    article: "Article 8",
    questionText: "Comment traitez-vous les écarts à une norme harmonisée ?",
    questionShort: "Écarts normes harmonisées",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra"],
    displayOrder: 31,
    isActive: true
  },
  {
    id: "mdr-art8-q4",
    article: "Article 8",
    questionText: "Où est documentée la présomption de conformité ?",
    questionShort: "Documentation présomption conformité",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "tech_doc"],
    displayOrder: 32,
    isActive: true
  },
  {
    id: "mdr-art9-q1",
    article: "Article 9",
    questionText: "Avez-vous identifié des CS applicables ?",
    questionShort: "Identification CS applicables",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra"],
    displayOrder: 33,
    isActive: true
  },
  {
    id: "mdr-art9-q2",
    article: "Article 9",
    questionText: "Comment démontrez-vous leur prise en compte complète ?",
    questionShort: "Prise en compte CS",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra"],
    displayOrder: 34,
    isActive: true
  },
  {
    id: "mdr-art9-q3",
    article: "Article 9",
    questionText: "Comment gérez-vous une CS nouvelle ou modifiée ?",
    questionShort: "Gestion CS nouvelle/modifiée",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra"],
    displayOrder: 35,
    isActive: true
  },
  {
    id: "mdr-art10-q1",
    article: "Article 10",
    questionText: "Votre QMS couvre-t-il l’intégralité des exigences MDR ?",
    questionShort: "Couverture QMS / MDR",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "QMS",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["qms", "ra", "pms_pmcf", "risk_mgmt"],
    displayOrder: 36,
    isActive: true
  },
  {
    id: "mdr-art10-q2",
    article: "Article 10",
    questionText: "Comment démontrez-vous la conformité sur tout le cycle de vie ?",
    questionShort: "Conformité cycle de vie",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "QMS",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["qms", "ra", "pms_pmcf", "risk_mgmt"],
    displayOrder: 37,
    isActive: true
  },
  {
    id: "mdr-art10-q3",
    article: "Article 10",
    questionText: "Comment est intégrée la gestion des risques ISO 14971 ?",
    questionShort: "Intégration gestion des risques",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "Gestion des risques",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["qms", "risk_mgmt"],
    displayOrder: 38,
    isActive: true
  },
  {
    id: "mdr-art10-q4",
    article: "Article 10",
    questionText: "Comment est structurée la PMS / PMCF ?",
    questionShort: "Structure PMS / PMCF",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "PMS / PMCF",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["pms_pmcf"],
    displayOrder: 39,
    isActive: true
  },
  {
    id: "mdr-art10-q5",
    article: "Article 10",
    questionText: "Qui est responsable de la conformité réglementaire globale ?",
    questionShort: "Responsable conformité globale",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "Gouvernance",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["gov_strat"],
    displayOrder: 40,
    isActive: true
  },
  {
    id: "mdr-art10-q6",
    article: "Article 10",
    questionText: "Comment traitez-vous les non-conformités réglementaires ?",
    questionShort: "Traitement non-conformités",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "QMS",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["qms", "ra"],
    displayOrder: 41,
    isActive: true
  },
  {
    id: "mdr-art10-q7",
    article: "Article 10",
    questionText: "Existe-t-il une revue périodique de conformité MDR ?",
    questionShort: "Revue conformité MDR",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "QMS",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["qms", "audits_compliance"],
    displayOrder: 42,
    isActive: true
  },
  {
    id: "mdr-art11-q1",
    article: "Article 11",
    questionText: "Le fabricant hors UE a-t-il désigné un mandataire MDR unique ?",
    questionShort: "Désignation mandataire unique",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "Affaires réglementaires",
    applicableRoles: ["fabricant", "mandataire"],
    applicableProcesses: ["ra", "gov_strat"],
    displayOrder: 43,
    isActive: true
  },
  {
    id: "mdr-art11-q2",
    article: "Article 11",
    questionText: "Le mandat écrit couvre-t-il l’intégralité des responsabilités exigées par l’article 11 ?",
    questionShort: "Couverture mandat écrit",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "Affaires réglementaires",
    applicableRoles: ["fabricant", "mandataire"],
    applicableProcesses: ["ra", "gov_strat"],
    displayOrder: 44,
    isActive: true
  },
  {
    id: "mdr-art11-q3",
    article: "Article 11",
    questionText: "Comment le mandataire est-il impliqué dans la vigilance et la PMS ?",
    questionShort: "Implication mandataire vigilance/PMS",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "Affaires réglementaires",
    applicableRoles: ["fabricant", "mandataire"],
    applicableProcesses: ["ra", "vigilance_incidents", "pms_pmcf"],
    displayOrder: 45,
    isActive: true
  },
  {
    id: "mdr-art11-q4",
    article: "Article 11",
    questionText: "Comment sont gérés les changements de mandataire ?",
    questionShort: "Gestion changements mandataire",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "Affaires réglementaires",
    applicableRoles: ["fabricant", "mandataire"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 46,
    isActive: true
  },
  {
    id: "mdr-art11-q5",
    article: "Article 11",
    questionText: "Comment assurez-vous la communication efficace fabricant ↔ mandataire ?",
    questionShort: "Communication fabricant-mandataire",
    criticality: "medium",
    economicRole: "fabricant",
    processCategory: "Affaires réglementaires",
    applicableRoles: ["fabricant", "mandataire"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 47,
    isActive: true
  },
  {
    id: "mdr-art12-q1",
    article: "Article 12",
    questionText: "Comment identifiez-vous les exigences nationales additionnelles ?",
    questionShort: "Identification exigences nationales",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["ra", "gov_strat"],
    displayOrder: 48,
    isActive: true
  },
  {
    id: "mdr-art12-q2",
    article: "Article 12",
    questionText: "Existe-t-il une veille réglementaire pays par pays ?",
    questionShort: "Veille réglementaire pays par pays",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["ra", "gov_strat"],
    displayOrder: 49,
    isActive: true
  },
  {
    id: "mdr-art12-q3",
    article: "Article 12",
    questionText: "Comment ces exigences sont-elles intégrées dans le QMS ?",
    questionShort: "Intégration exigences nationales au QMS",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 50,
    isActive: true
  },
  {
    id: "mdr-art12-q4",
    article: "Article 12",
    questionText: "Qui valide la conformité locale avant commercialisation ?",
    questionShort: "Validation conformité locale",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant", "importateur", "distributeur"],
    applicableProcesses: ["ra"],
    displayOrder: 51,
    isActive: true
  },
  {
    id: "mdr-art13-q1",
    article: "Article 13",
    questionText: "Comment l’importateur vérifie-t-il la conformité MDR avant mise sur le marché ?",
    questionShort: "Vérification Importateur",
    criticality: "critical",
    economicRole: "importateur",
    processCategory: "Importation",
    applicableRoles: ["importateur"],
    applicableProcesses: ["importation", "qms"],
    displayOrder: 52,
    isActive: true
  },
  {
    id: "mdr-art13-q2",
    article: "Article 13",
    questionText: "Dispose-t-il d’une procédure de contrôle documentaire ?",
    questionShort: "Procédure contrôle documentaire",
    criticality: "critical",
    economicRole: "importateur",
    processCategory: "Importation",
    applicableRoles: ["importateur"],
    applicableProcesses: ["importation", "qms", "tech_doc"],
    displayOrder: 53,
    isActive: true
  },
  {
    id: "mdr-art13-q3",
    article: "Article 13",
    questionText: "Comment est vérifiée la présence du marquage CE et UDI ?",
    questionShort: "Vérification marquage CE et UDI",
    criticality: "critical",
    economicRole: "importateur",
    processCategory: "Importation",
    applicableRoles: ["importateur"],
    applicableProcesses: ["importation", "traceability_udi"],
    displayOrder: 54,
    isActive: true
  },
  {
    id: "mdr-art13-q4",
    article: "Article 13",
    questionText: "Comment sont gérés les DM non conformes ?",
    questionShort: "Gestion DM non conformes",
    criticality: "critical",
    economicRole: "importateur",
    processCategory: "Importation",
    applicableRoles: ["importateur"],
    applicableProcesses: ["importation", "qms"],
    displayOrder: 55,
    isActive: true
  },
  {
    id: "mdr-art13-q5",
    article: "Article 13",
    questionText: "Comment l’importateur contribue-t-il à la traçabilité et à la vigilance ?",
    questionShort: "Contribution importateur traçabilité/vigilance",
    criticality: "high",
    economicRole: "importateur",
    processCategory: "Importation",
    applicableRoles: ["importateur"],
    applicableProcesses: ["importation", "traceability_udi", "vigilance_incidents"],
    displayOrder: 56,
    isActive: true
  },
  {
    id: "mdr-art14-q1",
    article: "Article 14",
    questionText: "Comment le distributeur vérifie-t-il la conformité des DM reçus ?",
    questionShort: "Vérification Distributeur",
    criticality: "critical",
    economicRole: "distributeur",
    processCategory: "Distribution",
    applicableRoles: ["distributeur"],
    applicableProcesses: ["distribution_logistics", "qms"],
    displayOrder: 57,
    isActive: true
  },
  {
    id: "mdr-art14-q2",
    article: "Article 14",
    questionText: "Existe-t-il une checklist de conformité MDR à réception ?",
    questionShort: "Checklist conformité MDR réception",
    criticality: "critical",
    economicRole: "distributeur",
    processCategory: "Distribution",
    applicableRoles: ["distributeur"],
    applicableProcesses: ["distribution_logistics", "qms"],
    displayOrder: 58,
    isActive: true
  },
  {
    id: "mdr-art14-q3",
    article: "Article 14",
    questionText: "Comment sont gérés les DM suspects ou non conformes ?",
    questionShort: "Gestion DM suspects/non conformes",
    criticality: "critical",
    economicRole: "distributeur",
    processCategory: "Distribution",
    applicableRoles: ["distributeur"],
    applicableProcesses: ["distribution_logistics", "qms"],
    displayOrder: 59,
    isActive: true
  },
  {
    id: "mdr-art14-q4",
    article: "Article 14",
    questionText: "Comment le distributeur contribue-t-il à la traçabilité aval ?",
    questionShort: "Contribution distributeur traçabilité aval",
    criticality: "high",
    economicRole: "distributeur",
    processCategory: "Distribution",
    applicableRoles: ["distributeur"],
    applicableProcesses: ["distribution_logistics", "traceability_udi"],
    displayOrder: 60,
    isActive: true
  },
  {
    id: "mdr-art14-q5",
    article: "Article 14",
    questionText: "Comment est assurée la remontée d’information vers le fabricant ?",
    questionShort: "Remontée information fabricant",
    criticality: "high",
    economicRole: "distributeur",
    processCategory: "Distribution",
    applicableRoles: ["distributeur"],
    applicableProcesses: ["distribution_logistics", "vigilance_incidents"],
    displayOrder: 61,
    isActive: true
  },
  {
    id: "mdr-art15-q1",
    article: "Article 15",
    questionText: "Une PRRC est-elle formellement désignée ?",
    questionShort: "Désignation PRRC",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "Gouvernance",
    applicableRoles: ["fabricant", "mandataire"],
    applicableProcesses: ["gov_strat", "ra"],
    displayOrder: 62,
    isActive: true
  },
  {
    id: "mdr-art15-q2",
    article: "Article 15",
    questionText: "Les compétences réglementaires sont-elles démontrées ?",
    questionShort: "Compétences PRRC",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "Gouvernance",
    applicableRoles: ["fabricant", "mandataire"],
    applicableProcesses: ["gov_strat", "ra"],
    displayOrder: 63,
    isActive: true
  },
  {
    id: "mdr-art15-q3",
    article: "Article 15",
    questionText: "La PRRC a-t-elle une autorité réelle dans l’organisation ?",
    questionShort: "Autorité PRRC",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "Gouvernance",
    applicableRoles: ["fabricant", "mandataire"],
    applicableProcesses: ["gov_strat", "ra"],
    displayOrder: 64,
    isActive: true
  },
  {
    id: "mdr-art15-q4",
    article: "Article 15",
    questionText: "Comment est assurée la continuité en cas d’absence ?",
    questionShort: "Continuité PRRC",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "Gouvernance",
    applicableRoles: ["fabricant", "mandataire"],
    applicableProcesses: ["gov_strat", "qms"],
    displayOrder: 65,
    isActive: true
  },
  {
    id: "mdr-art15-q5",
    article: "Article 15",
    questionText: "La PRRC est-elle impliquée dans libération produit, PMS, vigilance ?",
    questionShort: "Implication PRRC",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "Gouvernance",
    applicableRoles: ["fabricant", "mandataire"],
    applicableProcesses: ["gov_strat", "ra", "pms_pmcf", "vigilance_incidents"],
    displayOrder: 66,
    isActive: true
  },
  {
    id: "mdr-art16-q1",
    article: "Article 16",
    questionText: "Comment identifiez-vous un changement entraînant une requalification fabricant ?",
    questionShort: "Identification requalification fabricant",
    criticality: "critical",
    economicRole: "importateur",
    processCategory: "Change control",
    applicableRoles: ["importateur", "distributeur"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 67,
    isActive: true
  },
  {
    id: "mdr-art16-q2",
    article: "Article 16",
    questionText: "Existe-t-il une procédure de gestion des modifications ?",
    questionShort: "Procédure gestion modifications",
    criticality: "critical",
    economicRole: "importateur",
    processCategory: "Change control",
    applicableRoles: ["importateur", "distributeur"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 68,
    isActive: true
  },
  {
    id: "mdr-art16-q3",
    article: "Article 16",
    questionText: "Comment est documentée la décision réglementaire ?",
    questionShort: "Documentation décision réglementaire",
    criticality: "critical",
    economicRole: "importateur",
    processCategory: "Change control",
    applicableRoles: ["importateur", "distributeur"],
    applicableProcesses: ["ra", "qms", "tech_doc"],
    displayOrder: 69,
    isActive: true
  },
  {
    id: "mdr-art16-q4",
    article: "Article 16",
    questionText: "Qui valide le nouveau rôle réglementaire ?",
    questionShort: "Validation nouveau rôle réglementaire",
    criticality: "critical",
    economicRole: "importateur",
    processCategory: "Change control",
    applicableRoles: ["importateur", "distributeur"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 70,
    isActive: true
  },
  {
    id: "mdr-art16-q5",
    article: "Article 16",
    questionText: "Comment sont gérées les responsabilités MDR associées ?",
    questionShort: "Gestion responsabilités MDR associées",
    criticality: "critical",
    economicRole: "importateur",
    processCategory: "Change control",
    applicableRoles: ["importateur", "distributeur"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 71,
    isActive: true
  },
  {
    id: "mdr-art17-q1",
    article: "Article 17",
    questionText: "Les dispositifs remis à neuf sont-ils explicitement couverts par le QMS ?",
    questionShort: "Couverture QMS dispositifs remis à neuf",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "Production",
    applicableRoles: ["fabricant", "reconditionneur"],
    applicableProcesses: ["production_sub", "qms"],
    displayOrder: 72,
    isActive: true
  },
  {
    id: "mdr-art17-q2",
    article: "Article 17",
    questionText: "Comment démontrez-vous la sécurité et performance après reconditionnement ?",
    questionShort: "Sécurité et performance après reconditionnement",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "Production",
    applicableRoles: ["fabricant", "reconditionneur"],
    applicableProcesses: ["production_sub", "risk_mgmt"],
    displayOrder: 73,
    isActive: true
  },
  {
    id: "mdr-art17-q3",
    article: "Article 17",
    questionText: "Comment est assurée la traçabilité des opérations ?",
    questionShort: "Traçabilité opérations reconditionnement",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "Production",
    applicableRoles: ["fabricant", "reconditionneur"],
    applicableProcesses: ["production_sub", "traceability_udi"],
    displayOrder: 74,
    isActive: true
  },
  {
    id: "mdr-art17-q4",
    article: "Article 17",
    questionText: "Existe-t-il une évaluation de risque spécifique ?",
    questionShort: "Évaluation risque spécifique reconditionnement",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "Production",
    applicableRoles: ["fabricant", "reconditionneur"],
    applicableProcesses: ["production_sub", "risk_mgmt"],
    displayOrder: 75,
    isActive: true
  },
  {
    id: "mdr-art17-q5",
    article: "Article 17",
    questionText: "Comment informez-vous les utilisateurs finaux ?",
    questionShort: "Information utilisateurs finaux",
    criticality: "medium",
    economicRole: "fabricant",
    processCategory: "Production",
    applicableRoles: ["fabricant", "reconditionneur"],
    applicableProcesses: ["production_sub"],
    displayOrder: 76,
    isActive: true
  },
  {
    id: "mdr-art18-q1",
    article: "Article 18",
    questionText: "Les cartes implant sont-elles conformes au MDR ?",
    questionShort: "Conformité cartes implant",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "pms_pmcf"],
    displayOrder: 77,
    isActive: true
  },
  {
    id: "mdr-art18-q2",
    article: "Article 18",
    questionText: "Comment assurez-vous la complétude et la lisibilité des informations patient ?",
    questionShort: "Complétude et lisibilité informations patient",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "pms_pmcf"],
    displayOrder: 78,
    isActive: true
  },
  {
    id: "mdr-art18-q3",
    article: "Article 18",
    questionText: "Comment gérez-vous les mises à jour d’information ?",
    questionShort: "Gestion mises à jour information patient",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "pms_pmcf"],
    displayOrder: 79,
    isActive: true
  },
  {
    id: "mdr-art18-q4",
    article: "Article 18",
    questionText: "Existe-t-il une validation réglementaire des supports patient ?",
    questionShort: "Validation réglementaire supports patient",
    criticality: "high",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "pms_pmcf"],
    displayOrder: 80,
    isActive: true
  },
  {
    id: "mdr-art19-q1",
    article: "Article 19",
    questionText: "La DoC UE couvre-t-elle toutes les exigences MDR applicables ?",
    questionShort: "Couverture DoC UE",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "tech_doc"],
    displayOrder: 81,
    isActive: true
  },
  {
    id: "mdr-art19-q2",
    article: "Article 19",
    questionText: "Est-elle signée par une personne autorisée ?",
    questionShort: "Signature DoC UE",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra"],
    displayOrder: 82,
    isActive: true
  },
  {
    id: "mdr-art19-q3",
    article: "Article 19",
    questionText: "Comment est assurée la mise à jour de la DoC ?",
    questionShort: "Mise à jour DoC UE",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "qms"],
    displayOrder: 83,
    isActive: true
  },
  {
    id: "mdr-art19-q4",
    article: "Article 19",
    questionText: "Où est tracée la cohérence DoC ↔ documentation technique ?",
    questionShort: "Cohérence DoC ↔ documentation technique",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "tech_doc"],
    displayOrder: 84,
    isActive: true
  },
  {
    id: "mdr-art19-q5",
    article: "Article 19",
    questionText: "La DoC est-elle mise à disposition sur demande ?",
    questionShort: "Disponibilité DoC UE",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra"],
    displayOrder: 85,
    isActive: true
  },
  {
    id: "mdr-art20-q1",
    article: "Article 20",
    questionText: "Comment garantissez-vous que le marquage CE est apposé correctement ?",
    questionShort: "Apposition marquage CE",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "production_sub"],
    displayOrder: 86,
    isActive: true
  },
  {
    id: "mdr-art20-q2",
    article: "Article 20",
    questionText: "Comment est vérifiée la cohérence CE ?",
    questionShort: "Vérification cohérence CE",
    criticality: "critical",
    economicRole: "fabricant",
    processCategory: "RA",
    applicableRoles: ["fabricant"],
    applicableProcesses: ["ra", "production_sub"],
    displayOrder: 87,
    isActive: true
  }
];

export const FALLBACK_ISO_QUESTIONS = [
  { id: "iso-4-q1", externalId: "ISO-4", standard: "13485", clauseTitle: "Clause 4", questionText: "Le périmètre du QMS est-il clairement défini ?", criticality: "high", applicability: "all", processCategory: "Système de management qualité (QMS)", displayOrder: 1 },
  { id: "iso-5-q1", externalId: "ISO-5", standard: "13485", clauseTitle: "Clause 5", questionText: "La direction démontre-t-elle son engagement QMS ?", criticality: "high", applicability: "all", processCategory: "Gouvernance & stratégie réglementaire", displayOrder: 2 },
  { id: "iso-7-4-q1", externalId: "ISO-7.4", standard: "13485", clauseTitle: "Clause 7.4", questionText: "Comment sont évalués et qualifiés les fournisseurs critiques ?", criticality: "critical", applicability: "all", processCategory: "Achats & fournisseurs", displayOrder: 3 },
  { id: "iso-8-2-2-q1", externalId: "ISO-8.2.2", standard: "13485", clauseTitle: "Clause 8.2.2", questionText: "Existe-t-il un programme d’audit interne basé sur le risque ?", criticality: "high", applicability: "all", processCategory: "Audits & conformité", displayOrder: 4 }
];

export const FALLBACK_FDA_QUESTIONS = [
  { id: "fda-820-q1", externalId: "FDA-1", frameworkCode: "FDA_820", questionShort: "QSR Compliance", questionDetailed: "Does the manufacturer establish and maintain a quality system?", criticality: "critical", applicabilityType: "ALL", process: "Système de management qualité (QMS)" },
  { id: "fda-807-q1", externalId: "FDA-2", frameworkCode: "FDA_807", questionShort: "Registration", questionDetailed: "Is the establishment registered with the FDA?", criticality: "high", applicabilityType: "ALL", process: "Affaires réglementaires (RA)" }
];
